---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tvshows
  namespace: sonarr
spec:
  storageClassName: ""
  volumeName: sonarr-tvshows-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
