---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-secret-seatable
  namespace: seatable
spec:
  encryptedData:
    client-id: AgCi5rtQQPOH6oRHkRz0rAjPR8Zpph+4drAj1GZgEDI32hP2Z6MZfGJPoI8IyQWFAjBMGs/hMTdiZ0mDnniXrg6OJRPCY69b0I1BUMQAZBfieohYzs3GfoR8eVAmWKZG5qhjeX1P8zhVXvOWEzYDvRZAs+tqu1V3p4/VYSX3eAgEnMH1e/guXQeRZoZ7prQd7jrqvZi7Ysr3HrYhNEIV+FU1zs2XLhTlFTAi2abX/pxjm6JZzTiUHFlRfe1JAyZbAbAKSUvSKlhk7Ur537lDYlEAb4OxR/JWoAzI7ZWgdWyHwycudhTvT/s21Dyz4cySXivpsn5YttK6XZpezp5uqqGiapH9tKQsTuiMBh2r10A/ihmikckfPFVILsm2SanP2wT5PI2j9HsxqkvN2nyxA1s9KowPP3k1d3XcHP8S0HDrpfyS50ZeoDBq0G4bgZMoiFlSfDeN/VDF68MEMv2vELMucvG2S+LZsV4ftZgQvPdjU/XsQaFRtncR0VL54+ZGWetGyryH6vpX8ZlTlz/BRG67AaAtApr+NZIORZ+DIRqNJhVPFe0k+lnTt9J65rDwof9N9kMtx1AHBFRpIXMX1e6TfvDKrimThIncbdZlqMqrJgiyEY30dWLXoue+ytgXOX3eY4uJ9d4F+IRxVUbF8HLfepbT/03QkFpjE1QdT0tvrQp/0U3ZWgueLFnoQklYBwf93Z4Slg3gizi3VqZOfKQ=
    client-secret: AgAv3Svf2AfXOzz4V5MrKrqzOMc1/NlDXqtg5Jgh4wf2Nv8qM9GtciK7NDGwCSF2g+VBxgTrf6atOHoXzBm9PeGS7HEER7fuSavcjobP+/2GtUmbo+TULrI0NB6oOTJqKX+r2HfPpZCOwE9jT9ID4N29Ae0j+G/eeeZ1+c70hCiM0p8z7l5wwwK58acHPy8yJqtkltybkwVnUwHryTReJi5732sjI5JkwWrHhHLayQlI7HK6G0rm48kbiPAK4tDLnCnn6D0irH6M5iWmdrMLKRxQCDr7bSzsej0QygkFXvmvtG3LK16OIUO1WB6GhzIYPQ/7BuN2309jX/wBhesXb4ZrTlQwloJgGd3TRUDOsGaGm90c49z6Cui7MzhQgrqIzUeWiJi+ydQfdZnvd3kKwWNz995SzC1cKKxA0JnadMaiq0ldRZvuor1m+wnEYxeFYR2EOb6PRIjN5bmXOZzlfvDP5+YkSdaSA6Bhyb1JeVk8rCrYWfhptJY1LFt+IX5rjBu5jYCE/vSAE2aY2XXd6B6blNeHRbeTBC3DrVK5++nHpeY6yyh0JXoYA38xKMbzQfHgpEWY8aXXqmFHg3A3z86ELcMC/sFBYjlmfQ7cYDpuAinvuWwkjHmBtoTCYW2nP2FrLIH8C7/dk6yMNPTmpHSWaMte3kiJxkEAyAPKcVyy7tRT+0DXxgjEaj8QpEoq8vlXKxNS/duGjeRpgQSSaUgRBmqR+oUVfAC2hTBa1H8HOAWipNFrjz4QoNGmjoKMQlQqIsM/+NUo4BUfa/e6hZm2
  template:
    metadata:
      name: oauth2-secret-seatable
      namespace: seatable
