---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seatable-secrets
  namespace: seatable
spec:
  encryptedData:
    admin-password: AgCl9nnIU1FFlpBmVpWOfWVar7QBDmARpaEcCjTANqCv5EEKa5Bu3j1UccoZ1ACeWfX6j07KhOISInmIr5FQoHNe+cT1AoBGd0s/Oux6RC38eTQ1ASsBnJ6q+dCLDzEBmGM6KryhVA7+8GXume3a29ajG8EvmVC9o2318UIq9LPTSj7JfrBPZ9SrtJEVxaZwVMy6xjpepZ6y4HMy4SKHa0PPubZRtNxC4WiiV+4uwNTXYsmE4P39cFm45WmqhFsuljrAR+MIEoWO/+C3EfIa789k0tEW9A7tffEMAg60Z3Rk7qhEzfmrJFf1ro/TEvNSQ0SU5LTN52a26+CSxt26RG13gufmTRxRiWERL2m2wW4F57kM40dVoxatGrVdFnXAe8vvLtT0ZGtyVqt8fNaXAEz5W0PDMCuC26zjpN4ovS5cXdjKMI5GjUIlFF4u1I0v2o4jVVCXR009Zbft/VqkURqvnWjxmGRapt5AzZYvdUYxUMKFo7O2YaD4MG2d0XI0Wt6I6yp3sTjUix+JUfE+c7pUWESrSPK4y3EYVFAns92XwWca8pzsOaQtMRE49NgysZxG50fJgJ/qZWT1p3DRkZ2tehzLMSn0YcEYls3KrZEtdlr6y0buI5T1LnUtewB8DGu+OgmatiLJ2v+2Lj9yByAm6ikGreK7i8YOLSkA8RT4qMpW/xtanpbznFX2zDHLL8AQj++XByWOxpKpb8mlgGDX0VfoRxwm9naakNVwQoeINDIUSWTcFDeOwQLheg==
    mariadb-root-password: AgCzg1aIrS+T+gQWqnPx2CCKTTeYQ66QK8efan6mi3daxCOa5QS44le7ARiyAXrCgrEPmmhXpdS2jnP+DcoOHEVW+zlWp9XBAUJogMoD3DHENe9FuuDGjZsrZedTALhr8sL3i2xkDEwrl/skjSDiuPdpVIfbQIe86KjP7q1sQqCgzfSzZXINvssezLxdd3nTNUV3yLPZzCua96ghQC1c4DKSm30vcrrjkP7N4Gg8Mt4liq4/3cquO525L11Op92yolTu0TfIBrIIIl+sT1pst2y+BJk5JEUU26jxwZp+8gdLSerjvQR2SMoy0Sj1mtxw/KMyiXuQKy1zkV0jsh/DELvldsVoWtoiz44Mh7EzJvKpWJ9h5YwsVlPeGq6dUGMXL8z9u2GbKz25RpjpEcMokpRUQbqpv3whQad9R/4yS1lnak/7AUI5mtZIvQLR/iaEGs1LKbth/qQ0GIKWsSPrNMf7LkJnW3SGa0ZhTk8WlEBiGn7kvj4/icGewS1ZBMa3qAluBrLqOr/qRAOhmvpoCc2+y63AiBoXJR9yGa2PBf/fbkjPXHNZNnPhgvi3rdEzi62to8/7XT2gU5Bu+sv/Bk/YMfQT9dcIlIsoLG/43Ol2fyvJjjiQv1dEVlVxjmHGgluiY57BqknGfYulKNHwEVZilCwGGzIUhIwYYv6Jix5UEb23/FHYJqw0UcUMh5wlfxLlxxUwvI3Bu8iMTYMEj+g8lEaBtfiNb1tIaNj3+R7GgP9ahmzIw3RsUl6KJw==
  template:
    metadata:
      name: seatable-secrets
      namespace: seatable
