---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgAhf5p0pmEeAcvP6Tk7p7ftjcjlrzkBolAQ2fY3zOm07EytPAaVOqDrY9D6M7UCmovoVw/cPNu93iJ1ZCLefTuLejNMghgnHRx/wER/NanWG/TxYsBrN2IQvICLyUfHOoRIUHCEgth2MBUIod7DVItEdnoFv/fq3AGbKb0I5XcYZqkyagFJhdKoR5+inK3qgQqBSQ/G5NGwhP6LuF3AmE+tHzrNmnnP/P1Ggkedz65ig96w3cqmyK6eKgV8y92pdfnmdQT6hZ93F4anbKXzGa3RU/8wZyChnxWnvISORMLtNRHoF2X1KmAi2ch0UJf1Ct9QXM8qXsDhqB4sr+MIEzZOKBu/nFhUt0DYBMnokwOPce/B8ak4/s9C2/qhPDUTBuhMKUokzBBFHJkvafevHJSirgi6xEIYvbkee+k8qfh8dPUfBAsuQ6+rj9XGvRHSUB6VZ3YVFGrSJBqnG9TzFoduKrxB7w8BNfbRO6Fo0BN9zr6+nXLRRyhJCPU/NPN8ugqupkurRcM8KjjlONgJdVmKYuE7nHvzqcN0W0+ITtr5Vy918B9n7Am2OUobt96fOk8x85m/1h5mP8g4dNJjmTHTXzqAuAZgPx6RbPJkFPrS53yoL4YYuAZcI5L/CtWSNExy7tFBFPcfiCBOpc5EV9G3PqBjnInOHMwMlQMjdBxtuZdIyuE+U6MNJDJiLoOCPhUjOEywg3qzuRuHtxVCl1InFOJu2EY5dWxMafdi5AeN6g==
    CIFS_USERNAME: AgAV2o9FIwLpIP7StvvtLy/rC5N0zZsY31Evb1A9yR4cTOj5JmUGlY2uHskUqYbs8h2LRIp5pm/sxvS3jQUHa0NhIW7PT8ZND25+Bb0D8TERgizBN1cOA0emhqLEm1eZPTAXQGZ4HBk39Ms3RMRL5EN39fjIHTnTeF+XZWhIuDCrh3VMr/AguG73E/C/DKfblOLFNWVoVN0atXk8py+WUnOd+XsISQZmPaN08DId0hkg1kqjgovmunxKnVfftcU6XkAa2SfUJ4cufIZpj0M8bXP3uO0jZ4L7kukBzHfKtE8fKERJmusUcSZyQomxySK6rsCbd06/bLDNjFT2IrI4krYWHvY7j4wdLRYtSho6XvUpc3ZiJeYoQ+7ITMqmpkXQ8/rHbn3K9StOtL4x6xadD7W78jGNzLoXNmMcuIBR/5XnerSxzJd5pn9WirzVXwVGOApjvABKDRZtGrXjTnLWd9v/2bQDFQNAlbAZfCzGXsGERFzd6tj+dZG5sEXNXXnNfZ0ApsyzYHoOfqlUWYazdhf4QMH/HZJ5oPL+Odnrz5S8rvBu8O6fwyNy/jIDhoma8pwPkubbhsaVhcJsmdpezH8kswBi/3df5bIWOC1VDBILTJeP4zjr053eD+pkuAVRu83ro7AQbR/DTj/rX7z5AWmTDXUhUv1UQhuVb0OXIdXpSnmDvPpSdhWNrAvW1ZxEHBYMDu8cB5dJ9g==
  template:
    metadata:
      name: cifs-secret
      namespace: longhorn-system
