---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: romm-coop-coep
  namespace: romm
spec:
  headers:
    customResponseHeaders:
      Cross-Origin-Embedder-Policy: require-corp
      Cross-Origin-Opener-Policy: same-origin
