---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-data
  namespace: xlab-mgmt
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
