# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: powerdns-api-key
  namespace: xlab-mgmt
spec:
  encryptedData:
    api-key: AgBl6JQaeAF+2hFVLhg/mr9uBDPuKCxW6OBg0Et/NNPmoPx0ki+YwiBjdXXBcLCRFgMJucpG/wkuuav3MkmjOz4SJfbklV/K4edZldHzx00BD8lpovC3Oa2z1YPiYK95nmkeQRMOMsjdrW6MSakIPN8wfDV6XQwL/CO3JMxj8YR+F9yaUFfJe5tQhYk0DdQP/Xym5zyf2GilM1jyC6Iznnn0dGG2yE6nXjJGbNs0vP7B69JgEjROJjcIjf6AJUuCaJE2Pd7F5gZ+PQ9lkwsMOLjZOL5JDS82yoWnIuc4nrT39BgxiOTbULQ0Rh28fcW8xTRXiSCHfH2Nb741ZMUxeOQWLIjYEENRovTAZx/hO4cpTkzxk8bs2SI1T473q4OzHmu6sjgdz9yrIwxpc4SwQBTh6sDmRzvWryFxQumu9QcCaBabLSlejy3gsmJfiq7iL/7QZYms5+tOa5TC+IPsj5KtltYz5d0v6KL7uRtOkYcpIByi3sOXhQ8JLJi6WlgQRrYtGQE0mTH8bzb+CtBEdov0TqmGcZOghRkWV9FXxNJQKNhWi1RksMS1hhfXgY9ntJghE/4i9joe3lXOan89/ebiCxcRQSY6JCh+i56ZgidUT+uyY/YGnIfxU1Ki2tQjCvDDZXeBIFxDjVX53kHNqrYo1F5FoX8iOHlyHyz/hTHJN+nFwgfFxvzr/OI+7axPVjB3QfSNWEJ/aX2jFvBXiW+5RaTVEOS7TjFVBdhysGF3n1Bj1GjuM20LzzoDhTh47zrjbtNY3fqPzBXshs+JTM6j
    username: AgAxf/j6bG1dz/15ZS2jVX82xdrdyAVFG0WyBbAJQGCPMUmkZd46IVcBwiL47EP8P8gaLF+ugf0689fKMX8YRbFEfXbIhXlg96u901R/QXHRqCu6iKWL2GtDdBdBBQzzb4fBv8iLIAMdYXfYU2vltYMHBYYdK1NDZqrFL3Lz1PaR0C2DX5OCCkpyWFa2q2rHUGXHMZaaDT0jurATbUlrNW2gqcCWBcl+fNteEOKpMVGAvA45FKIMT/ENbURXIHExaHrXtze9xxQlFN1Ic3c0rFcT9kHgbB60QvGass38UFQmQYiiHCB8isvR9avEOMC48Sh4TXDvFuzgqg3NbMsWZxHldRSE928GBUvyMYOiPea2iJaDdN7SeRCKC2Lj4oX/dfPqj2kV61B3ZBIziMwSOKMObPansC9SL8XatOddrwcGP1gzY+jIuowgaurc/2LRBEIMVfBKV29CnJoQZAhhn24IJkwDELNgYxHxWB+GhNJjcbjXFrB84K3jVUgPj1vdFqFhS7kgazFPJBGmMEbPU2Y5bEa96D+rygjZfJVhe0viqcrjMpIFXWYb+SWbPUBMtrHWtio4fhDrHzddjj6b9tL54Rnqtjoypkrac9mQmoRLmvESCXd40FZ+uJgzBoWif87Zri66EuGm8RMUQHT41DxHc92Ua1E7JvOSSicDMtlMDXaStAULGAL3UYHA6WHQgNl2k7fGNStQwlLk
  template:
    metadata:
      name: powerdns-api-key
      namespace: xlab-mgmt
