# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: powerdns-api-key
  namespace: xlab-mgmt
spec:
  encryptedData:
    api-key: AgAk+aYrRVcP9B9+jxPeH8RyBbGlwiKWiaYYBFMDk6F0D3LepxatOWtGMjp6b9+jp/llcP2wBBBDo81M72wfGO2Ljqvuqqb7wxcF9KfPptBewp8tGcleBtPZYo2qAyZDLjiyvCFbhr2LlOcz73jwH7OG6wOTZeT9+pqtmm07Zl0/l6Uay+oJXJrZvCT1nxT5w0C/ONP+XYsNbIee0TK4diBwIrjXeggdsfblPYGpw4OcTHR9QohXco/g/1RNkTp83wuXD29dtr70kKdrh3qX+HTQhFrHTu+m7maOUF8gZsIZoLKdafo2doRdzFu/Abnx5yacbQbB4xK+lx+x781T/1EqyJWzOHwnTe3thyvnxRo9yhOM5LIylhGswEUBVAw/q520HaIoCWY4msVsKZeSbvHxUCEIWKGOmHLiBZTHP/IV2I4l4kAzf1zy8JPmlVw8l2rU8RPda/8Qa6L4HJf+ELSPOqL0yA9CuG63O0hLWCXnwjYGQoXn8sJZrmUT0sMoFbvOYFY2/NXhoxOYq8EcGk0Dfog/9IWO0HpqcAyJlY/KPV2p6bfMuHN/z8bNAxwPYKd9ljHT5sfiuvFZE3CUFlzSY+kZUFS+C5SPXM6i4juP3SNoSMmh0zw6u/mTpXxgF49hc3i7c3kYYzqOhuyLOyuOsO7hKTbsZCYVJCRvJ/1Fganpq0C/0ongG/ppI9KhZjxltbBq+ho0YatReFejWrTGaqQy50rJ7LwPhzJs5KeiNDAzC4mgChHBODkbCbKK6OkrxT3OZKNR0qOYIjAamDeR
  template:
    metadata:
      name: powerdns-api-key
      namespace: xlab-mgmt
