---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-dns
  namespace: xlab-mgmt
  labels:
    app: powerdns
    advertise: bgp
spec:
  type: LoadBalancer
  loadBalancerIP: 172.21.0.53
  ports:
    - name: dns-udp
      port: 53
      targetPort: 5300
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 5300
      protocol: TCP
  selector:
    app: powerdns
