---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../atuin
  - ../craftycontroller
  - ../dashy
  - ../garage
  - ../jitsi
  - ../linkwarden
  - ../lubelogger
  - ../mealie
  - ../netbox
  - ../omada
  - ../paperless-ngx
  - ../rustdesk
  - ../seatable
  - ../termix
  - ../warpgate
