---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./atuin
  - ./craftycontroller
  - ./dashy
  - ./jitsi
  - ./linkwarden
  - ./lubelogger
  - ./mealie
  - ./netbox
  - ./omada
  - ./paperless-ngx
  - ./radicale
  - ./rustdesk
  - ./seatable
  - ./termix
  - ./vikunja
  - ./warpgate
  - ./matrix
