---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-s-data
  namespace: hermes-s
  labels:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
