---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.20.3.201
    path: /zfs/system/loki
