---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: loki
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
