---
apiVersion: v1
kind: Service
metadata:
  name: loki-metrics-nodeport
  namespace: loki
  labels:
    app: loki
    app.kubernetes.io/component: metrics
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 3100
      targetPort: 3100
      nodePort: 30101
      protocol: TCP
  selector:
    app: loki
