# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-bearer-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgCNfh4iXSQy6Vp19jszMwBOeXZnaaD8LQ2JvthjgaBBz+CK3pKK79V2bGSqGAvghO6UfyYR9ymjpLJnUAHwIwIbQQMc/E744mCJwM/W66kWyaIymw57JtTSuvGd6zzKntB+Ybhh/rXfvZNlcB5gwPPamJo+PHC3LscyIo+wvNaV9Un84QJGyF6DpRmjhJ0GHrteU4yPwChSXN0qWTFv+IZSu1sNSZWoWDP5d3gvh/JdUpLDvmJO7SdNDgmAXJUXX9OiibfYr3+85wh+/kzL8xRpglADZi2W5Eu74ESuOp6H4QXEogTVSs73EG+f7RVaYSNt9NrW7Ga7lsDtKvdeJhfIkdXly0Ypmz5Jsxm96yn6pNTzafdxhCZ0J5JhQ3HUKQ/azD4VKTASDxybraGvTOaiUUq1plvcWWyagvRoEU8PHe3ijjmLuU5vfpzPlIcu8cTom0n4HoLX9TmqkrqpONgR3aqTDNwJkvw/kF7jodE5FTfjM9b2YPHldSALGkzVzrQNuRQCtI5C0CC6J/WaWuNpeFs4DquktH5+BpZl/aK0wsSc7MasS+eHJqGd4Qajy9j7DbZoK89iwdX9aYusKkYzrNON1xE0PGOI8X0qFIa24XZECiymqNw23HBPD2UfG/TES3Itq+00wwNMySTg315EJNITiYC2B1NAoHmJtzlqCbtwKfmQb8LBuT+DfrPLlvL0NlGM+x6DHA517FfWbSoQVFYdYt1gQ37Mb5+7SVnZKwhLHonze6R0EfPEDimja6YBWBXmzAFrmdr80pV4dFOlDXIOAIfO362/jqDX6R9iYCGu10rwl58psVFnQW/TUvHPngx3KLgG1eSHPUc3g9H2VrKvaTnmT+HFVyqkC0oGO+b9V6QQg+gsn4SGT3jgyXqgs2Az0dOmG7o8H/usd1e+DZvNtpLRToJ5iriTrMT296ly3d8WHQQ=
  template:
    metadata:
      name: ha-bearer-token
      namespace: monitoring
