# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: snmp-community
  namespace: monitoring
spec:
  encryptedData:
    community: AgC23cKCb5RwQ91gP6lFJDZiiAYQLv4S6Ob05yiLECxmNTM21IwNHNcMurQpSw+lrezIrj1Aly3/SKbqLa6W52TGOzeHfuku9fc9k45HERRfdVHddroR+pbHD7Dq+WtoB2zINoqQtCk8Jjh1lX4s9trTGzkaQA6CQ8bL4AhsCU1eSXaOMkOE77JbilanDZOBfsj6UEtjzT2GHoirRjeWzMXFo3Tk9NIcidYBTizAToZ9t51Ej3HGWt290x3JDTXX7qUP/O62OvfQNnmG2hu+CgaUIdaE8JZzwz6wSN2ppeBI26fB1p2dwLkB2WtO13UWLcl7mDlIibJdD3xMvuzmm5o8BC2us/1N43cmXYW/oG2q5NTw1cF++E3Sl7yAGGsDpdzukEsbNmukrO8rcuyxPabxms26gcrU3Xt+SmFmeF6pcdkkLKqCH63VgBsirKq/0SofZHTvcIf1Tv6iC/PY/OA15rz8VSH9jI/chbGvlngIte6861dnjvIuFtsHmnUsvZ+TrKFFMOq1OLNpBj3CRQ4aGxPXd+PaGYMPvOEYXHVqEPUxtMnMua2uYVeDADZt/jlpA8z/nmySvw0pXlGegeYoYMO3j0XtgArb1wZdm/Red5s/gV8UO8xbFohHfL9n8lHnzdL8dPE/GmC2GC3E5NVYW961avh//b7yyn1T2BoYOfgXKNUYge1ftlVj9bo5h87lZS03aIKde4fanNOe5ir21Fk8Cg==
  template:
    metadata:
      name: snmp-community
      namespace: monitoring
