# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-bearer-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgBOQGliUcfhwpITcorgsJe7PjijY5Md66GCfnTQ6G62NNnyipuM887ZNvqhjGqi8UGFo8al4nFNcDnal4OckCbpt/YILHQC9a0jroULOgT27GJtnzyO/LvWQ/buOTUWpwx3nafUt4m1H1vMiX274qHtWIzGU/DxHomAkJD1ujNdsLX2VZMRyII55/aZgOLuMJVO8+SA7rdOtSnKms6C7NS4uwJNR4TxfyqMRYgYzSIm1BzzN/t0pyXkiQyXJiYpTvm4A2nS1n2kEsVqh2Cm8yROEtbhST/teKalEXvz/mhb7/iFopQxdq4VJ/X/F+YPp/wLJs1+OTc6x0dMRZSYZ5ITSYdZ1RvKf9V7rRk0HWc8B9kmNkRTGlsoiyXsJAV8yemFLfGdU+aZ58fDtn0enORXYYjzkSawynnziAvuk1udmtKZH/UUz/bOxIsETQXPxMRJ+8VnXFkeiYF54nFY/QKmzuQMBJaDhG9B6ICFix4fTs8B7tUjY/2mdT3Wj8s8c+3Q3zJD3yb7tAU/M9WZRXIbglmLcmIE5r83Spv0yvezuqVJTPoPk1DMIZziiQVEsw04nCL/cf/e0DqVbqIE2zV4Hfh5Gk40EY9sZZSVnOeFFJt4NblCiDWyEZcIKL57uZ2h74CMKbwYSTThn2HjZvTn8y95c4Ppwuo04XUXfhQ4DKEJ+mlvYwEmTwriZQlkAJSJkquZWxvcvrtMCBCbIiyon1nHsH83VQuSSmwJ6trcpqUGmghTOBUdCU0XqR7Y2Uq6lIB2+EOZeEuRc5EW0n2mUnXh7uIKlSHIYClGgyuY6KF1xj/OEjXgRAel6MQ7Sk97H/dhlpHyjzX4z/X6BatMCOApaQxvXj7mzQMmBEh21k2eIOt9lb4mj1RhFUAKVsorUTraeXCtI9oSjppQVv4sfdT18fBXxSQWt2v+XIaNrwz0PfArOhM=
  template:
    metadata:
      name: ha-bearer-token
      namespace: monitoring
