---
# ntfy exposes Prometheus metrics at /v1/metrics on the main HTTP port
apiVersion: v1
kind: Service
metadata:
  name: ntfy-metrics-nodeport
  namespace: ntfy
  labels:
    app: ntfy
    app.kubernetes.io/component: metrics
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 80
      targetPort: 80
      nodePort: 30103
      protocol: TCP
  selector:
    app: ntfy
