---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-music
  namespace: lidarr
spec:
  storageClassName: ""
  volumeName: lidarr-music-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
