---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-ingest
  namespace: lidarr
spec:
  storageClassName: ""
  volumeName: lidarr-ingest-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
