---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lidarr-apikey
  namespace: lidarr
spec:
  encryptedData:
    apikey: AgCkIhLb++/yKfqmLyIQs7AQ9a6dGzwm6vAtlgs1cNBuhQyVoSL2XXjdgsyA5y0ZKhIOusHgTaLj04S2A2w2LSk3DyM46EZ9v29nC02D+yNIllN4BUtLzSOCm60IRjL/Vy+dLwPIoioNDbBllt3UtKUoJD2Z/RBYCrtLUiQIdycI7sfl8+JWm0wrsI361UpZdngDcDKOV3mpguRNsInECFiDjMbOh/Fu7RFapfHHwWJie/gk8gAPYxtgFP8yGfliFm3cFiaTPL8RsECmtSX4ajGG6sXcF042A1qyfdOz9GkEoMFo/HpKSMY1tbFlayD+QMpc4JLD5Qs1PmltoZTF4A7jaG2sKYIX75/k9zSekHbsS4bAHgL7b3S/zWqMQsXkSmzVIoqGoQ5nOeU7tSU4aU8WuIXhM3fOaZ04R/+a8mSmtlPhOu/vDCZG37n/hHgE6yL6hG5k5lF4Z9Be9Nuwl5c/8yw1FMiEpminZBK/8Xbxy+KGhAsOhya87BLhHqlHL1/UhSmUATrP2l4b2WeuLdz7kPCBQeqVGRY7p+BbjCT7dqZUeDDBe3x+SUOZ843Nu1nyylCFTL4ysYRh9V9AYbrqO+ylnENoOalD/NBcV+wPIsCFvCCl5xoxd5Ca2prMhlnlt3SQI581GnbVJjWt/TAsmhA6GQ9sggdKq1eBIuSLIL4+PC+cSUuaGbLJbzkB4xhFX2JiHBb1XMvXnYiIEmCvSg5rvsPV1md3NZiNljTcDA==
  template:
    metadata:
      name: lidarr-apikey
      namespace: lidarr
    type: Opaque
