---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-ingest-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.20.3.201
    path: /export/zfs/ingest/movies
  mountOptions:
    - vers=4.1
    - hard
    - intr
