---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-music-nfs
spec:
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.20.3.201
    path: /export/zfs/media/music
  mountOptions:
    - vers=4.1
    - hard
    - intr
