# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apprise-ntfy-credentials
  namespace: apprise
spec:
  encryptedData:
    password: AgBTN4lk5TGvQq+Hc44eFBSWoJlXs7gqdrRmAhCfod4YkMS5r7MpzLIVP5yrNTY6ZrvcPXSMqFGY6eDYVGOcilKfzBfZyQdysZFKcGArJmx6MsY8o+7MnJrYGc+38OgxTN2pUw+J+zabmFpidpAiA4zmUs5lmKpLZY93hCJ3lUqAmylUWks4kDgEqmNnveIwMhE6QqlTHlsMNGsOLYCj3mnO/hCW/LF7AhBf+ad90cGrYggwvmkPm/El5yrA68GMTZYh4RaeeqJWD6HBQprhr9be4mekZAeiJ0y+k40o0UgA3xp4gtPt4VaDERPRyr6lk7iOIVRlvIVLVZRAfQJj0UWq83ua564slmIlAs3Sn7mZp1Z/i8Qz3nxvyemoKhhKaI8uiokSV4Os918CyMQtbELnUMMls//mj4HmBW6ijQo38AKbI4eV/ON75AtJHiMjrNhszTSBqx+hq399WCGWz1tPKmy+9KYndzuA4d8ieH8ThYnPQuPO5t6Um9y7X+/4Xz0Lx9l/+Tf7tQULd00W+ss+JNLki45dnjjfQqbaFw/AHn8tRKYb0ytkDMcGqz3e/fOu7Kq5k704qKnZvFxQm3mabefTJwFx7GAwR+jL+Msuz0F83P3Ca5LppCsHoJKHrprVu2nWHcYGZ8c5pT9kfB7+HyDFCClCmhf5oZHWIVT2vD7QscMqEJOggh59giP3wYBzVVZXvjPyXpHvTWS05TaJo7EMY4M6HA7TDL3qgTWR4SZtAoqyaZuDMS8PqYuvWU0=
  template:
    metadata:
      name: apprise-ntfy-credentials
      namespace: apprise
