# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-api-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgBIhlOdE990ey2KKDC/7++W8H7fjmM7eZtc7PCSWuz5JpPyOH8nzmTP0yeaiGp28leB6K9dY1zm7GQf0e3+uopoIa/v//AVySPeJB9eVKc5aFw1CyaLvoVgbTyUapCY/w/hiSOcH5CGBSid6A0/dEnH4oDw9IcOcBvxmZkF03PQiJED4Y4AcZEs0kibXlohJ8ZojG6seUz32l+o8qDPI0a1s9uN4LQj1DzZFgaOlSkaJdItZICNTUoi+B39X5HvLUX9t7TsaMUJ2RTVet/qXmL7DI/+9cLAAO16bjLhb/pUuqIyHJwb6QF+JCEs+M2m4s0fXc59VX0LqgmhVvLsVEEhe05308Wd8k3jzCdWbLNIXf6Rrha3zEmvmzYY/+xHzcbQPnJaFaU2QKeEVIxBs4n1pFK1DRkA2+6OG8Kdh09q1mV33vjPK7A25U50vhbuhDR20IS7Rk9lLq2G541Z0HKEKic+2f6Qd9ysTsz+lW3HPnz2GyH6aXQHeVCISTqUXcUHT8T0W+LHkQ/I/MH4mGmbZA6ttqT2dtlqUGrWBTR8rvLBsdaBmanOVRGuEZGfRsb9cIYyLEH9x09tK+YW9UzpWiafrBWVMbMVBhdKQf/cL7SsQg2iaIReJxw9x+by6T8Gof+8cSD0fzYkzuLqt6c0+Pn8HcQEQYwXHW3wajjc3CKb8bamDMB+/hnlNdS6F/XiPRl+yqL4QIKf9OI+hX8jIosIWbQC47XreDwLLwFXoKik5QF4X2cl
  template:
    metadata:
      name: netbox-api-token
      namespace: monitoring
