# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCDPdyCav+dS/YRUFFXX6I8oD1OqGlijaaef6INX2bFS2htvROqCnZ9X9mKTS4XZy41IIGnTq4lnRmn6M/9gg78YBBWgWxUQ2STYPe+0MQS9fNn+LKeqJM3JXudNEziIp+a8lImuY4zdew7F+21dlFhxlmtgaM+CXRp7cbWIhh0ORbagxSzBT/8d9DVkWhBSZwYkt6ndFI8QobHAlmYT7mlzH2jL/38GesCG1XRWm9DA7/yH2MHgw3dsg4H4mOjLm056P8PtzkFo8I0lD1WN5e4du9rRd/VgRjqtHj0OY0AcakTX4kK+zEwY/CcwKlxZPZxzQ8UPw5gpiTT0oLPQsC0CyHdl0yIu5HRugQPwqKCZF4ezH7TmYipHawzxWRNfZxhfSLBG/BNMbTiMBZfAWivp4snYV+XFh8IQo11VQL1gUD04QB32kT2KNDcKRmq/joP1UakytEUlVJFRGcVI5HEsEWK9NGDOpyGqTOw6zxxj8OcB0ortYn3kVs5+uewKfazPzOft25jQeaYFhbrxXu4kDHRvQWqw2vz6xAEtLGyjo3rdv/jYnChCQ3Qa0gBNTkPWEZdljNYqjd0DMKJSJc1Ui3Fd5kvOMbkIt69zmz0sJzTouSEet8q6EgMfjm+NTUvUf3PgQufb+BDWefqt82vbN3VQbYwnCDl9p65s9A4bh1wUY3VUK6Z1BVNtgaxOVHS2WKWIHCwDiLlsCoDdvceEGgs7gadWuKi2+IRDFw4ye8NlQdhXfbo
    admin-user: AgARKANTdrHsommX79hyxLxMaVdBM1RlBIesqtUMW98gfujefmrajn1ANV01XPjnQe/K13uajNvZqL5b/GGwcwHkeyyeLmipNdbWqS/ys6WWhQ0vqRk2QSuD7roiinFt13m4QVkQXJCN54Ln+vrkchwc9DPvIVXliZaJzg9dlmO57ViWtoOZqb1dRSVj/YafjhUFCpcWph2dE3Ui/+RJ5tAuKf/u6wAV0zlmAppEsys7iVLV/4xv2PgabBNwSXzbwfhhseI8vYlzcM7p/fUwj253ouReaOTcGyzOKfO+PuANTPSnQ1r9wNZjSSwknxjieatFJZuI9swPrtU/kCF6j2GE9IebhlJbgdMdLeybxKBWNdy/a9EihC29Gp8D3KpDE/MqyI9KJlfuzv5DFHuCxbR50owdVUJeojfbMj42jArS5TlXhr9H1ftf4nGKKwemXrg28MQMUPLaqjZ9N9fPP+K7QeH9Ps6bR7uMIcpYGnlOyEa0HunZyNhkylE1xwo0dBMuM6F7Q+VUa/UgQG763DCExNVKl+qx6SC+XlGRpxZ9L8YH0iH8HvLDxOk9eXvd57EF8MGkxRTAn2yi0g+79tmqFfhwRRpqG5QbGIy60DA6jXm74M2illYXl5HrsLH9LU2DxXTOME6WEPeAPe1/bLlBdrT3kjjbF+Gy3p/+akvm/1YerbjN1mva/MqmRYPQediEq/M=
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
