# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-api-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgCOcn8kkAK2PVCeAU/Rq4yOjhnV3uBZ13EmmNzMygVLMEg284gwwQf4sPsITF6CiEYFAP+q/Aat2SuHWmINZlRQonF1k0iREP/1y7E7rQVssBqkBVE5h43407S6sEJXD9j0QU79rKlNVkOLRR+sU9F8kfE9/WlDH4QSSPba+cdn9jvRPpUKvrW1gBrKATZ9bu2c6cLY5lNlrufWIjeQlTqUKUiT9iysIb4cUsaCPk2z9iuiTfX8tVLY3ACo+yu8gw7doFjMULliaBmqZ3NZ63ixyeCKkYPtN1KVSZL4fBHUy89Aab8pD/TYqHu5geQCbLEsHVLl5Q/7WnKEudN0QI50YolNtiF6aXC5Wllc0Pz51KoXrACYcBP9o8XoLhLv9ArDYU39qgsLvvUMP96iYZr5e0MOSoIXJnCiAxyxXidpLNfykk4Trc/zYi/Vgw/IxgWls7/gBbTTRTBxBt+tlhXax+LhwkyRce/ESNUrOrqk3ROSZ899QsiCvivx8k4+SIh5hx0rW4FhOqwkUTVgpidIrkWN1v9ITnmjS2ly5m0MnzHtSd3g31vxzV+gg+fsgi1cWHrB5BuMr3rqRB6ddtuInERz2w+GCpoB6M/GRrfyYTr3Ha0RbrpprpCgeIUS1u5dyz+eEFL+95oLjP+yG2MJSufMJIdiRME/pA0wV93wg2pRb4FsS+nia4gwcrGQtK9O+YwzODw/nTaRIlBVlxCfE9VZ6rZCZIhFISNO1e8oss1zpanKNMBaRwFU8iujToSocZmrmA01Oz4=
  template:
    metadata:
      name: netbox-api-token
      namespace: monitoring
