---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: warpgate
resources:
  - namespace-warpgate.yaml
  - pvc-warpgate.yaml
  - sealedsecret-warpgate-secret.yaml
  - sealedsecret-warpgate-oidc.yaml
  - helmrelease-warpgate.yaml
  - ingressroute-warpgate.yaml
  - service-warpgate-ssh.yaml
