---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warpgate-data
  namespace: warpgate
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
