---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-admin
  namespace: warpgate
spec:
  encryptedData:
    adminPassword: AgA/PutDVm2C1q4GJp+oQPiVrdx4YA24tVYZPAiQkRre0sNBSDcwWxZJjSfZS2vkiGRKUey+/UQJgZ+NIOdP0xcnUop32xKG3kvhCZjYmpvdVvdyDbapzNa3Tj0cBEnqY52MMuP1U4kijpFB39foS50eQmZZHrpBXe13G+dO0clmMxXwK40+6v465/9tNyvHDKrd/osmURoWywMrQdG8hUkaE4+PklgFzjoJDIsOUDSKUpKfUeGaUvAOY3RgMXQ73yFig8oCI6GD+W2zmGRTej/orRz2XJSOjq43IrDhrpPqfkpv2iKtXov2JAb6Un6dplwYjmfiUWJ0ag0T1kbWIpEIFH+dgJKadp3g3JZFHtPy+cxq8JmuCvN7dKL9c6GnJAljuaZQTJ6EOLwp+Btp9OOO3UqnboiCaMNb0wPB9bwhnG5IC/rPJoz1d0CR3osnANMEN/yo5JvQs89YQdukD2UOwiu3myZO7XTHTWDhkvemcU+C+Icdgg5wmVENdx2B87TyxkNBUEh8gK1MOdGk+i5dEodFkDrxjO/sVS2dU6L6g0mVOkxBCNZTalhGWtQWvz3Ci5FYj8W2q+P/fmcyHmJIv386JjkKHJRGxmJwr9+m4nRPugycfXlphQZxOIn7zP5piVhwxmQzBzi0ocWAWR8L08A2cwaJFGO6FzcbXxTleUtXAYo1ODJ74L+CXLLrYyPi/8Vj1Udj92VWfHyZEe1odC1xBUDiFpBuEeUd1svV4LAPHYVcqBc/2JBd8A==
  template:
    metadata:
      name: warpgate-admin
      namespace: warpgate
