# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-ssh-key
  namespace: windmill
spec:
  encryptedData:
    id_ed25519: AgCksf+7O6E5lXKwV/3ynzzulgj80XuwOKU33exOG1NHuPRIrJZY3vgSXOj/U3oWLH5kfpkrBOn+b7dXyEV92Tp1O3o2LvKf5+XoO7EOHXPFjNq+gbOzUcOW29ioJfDtVoKHo/sulGw0hGxHxVH/yRZsx1cZVh0DecF9Sv9b5iPGsxTBgDjUbS1BEUFgZieU4PLy050Nko8RPJjKU3HYKwELOFvga9BzAyUXlwwsHKkE0tMa7u7X84bDCdOPQicUFdj5EPBSKTcJ/e13vuMSNAMkm/RUrpcj/eQq5227qQ7rOXh1A+J3nsr4TBGhMOJ5dVKDxe1nv3uij4RGDWvC3rXMpAwkWBAmX5macVGi38wJl7ecdjv2maJKWTENux07BRT7Gf5Mi86L3kH2BzpjYCUAWpuUqmiYmn1+RF5e+v56LVpznVcWxbs+METn0UhXrSa9Kyx0k8n/Mos+QqS1baiULic6npB9CHgH2hHfiMv8EojoQv9xCVfBaMikirz8F2744aJdzdp7uZ10/OJgrA/xGrmy2dqbzr8vwv2WZ69LvMhGgTKDdugfzi1qyX5sc8Fz6OOpUMq/r5JN0a1LeNzgDfng997wi0GRMdt+KacVykgNvnpUozKGKWWCZObl/QHN6dWLaJzEoF+9/VqsG8vrVX4QzsI3IJ9ok5rgV+sZpWjAhm8Dlf3KSMrP5U45s6jF7IrshmupcyOmlvWm8MLkt1w6BhLycd+2a6Se05LXEDgAMSCCzsJ/zKJw+K32yHcAfHPx8A4fKImEMBoldtHKP7f9OdY+C5AFCSt+YSieK+vbf+7kESOFd8OpT5TrSqxUoQM78DGiJgfE00yn+HIE7QGI0cG0VJ4hMh1INgNFGKXktOCGEG2EsJJ3OYopggcPLF/f7UXUK2yZJ9KqZDEEv3ApBa74/Fq7ua5TSqtsOAHiIqit9KmD5bTRolCiWaeJ8klrXCigZLV9DTRUsCZ41c91EQj4eM/Vq9L5mIvtQTzHHkrOG10M2OLusRzokKgsrkMXV2r+7Yd2Nr82cxcd/rUEsyZ8W5KRXC3lZ8QcQZgqTQLpa0g1kIOVfSgfsOX7T3A1bx5YUh0eAv2KA/q12F1a80Kjb83tvAfaYEE9trUR/P84pp/lTyvpY1OEAZNt6GcAUJ/7z+YVZRJJRM6GZ7SqC6QiSsDWkLv5QT9VgjSbaT4L9jQf5vqvi0tJk+QzYQvnk0+FTJlwpS0rOOFUrkp7ff5edBILwjc=
  template:
    metadata:
      name: windmill-ssh-key
      namespace: windmill
