# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-postgres
  namespace: windmill
spec:
  encryptedData:
    password: AgC2wSe793GTV5Nk7M36e7HRGEsWYgFVcBWOFzaJjoKqn9Rz02yYJIHaV/BkstYcHp53INGEP7H4EDx7ok4+0x30MCpiY6dwMf+neShp+pUrSRJnrZtW4qVhkcJMLGRcsKez+Kov4ZUNbm4krc7m8ecMLUDYTyYRVVAko/Hf1nk7OkeuYdb/lJYrzyz//Ul6AziWnoyyqqMbG/rM1zYAhoG3OseydWBorZzFrMby2MFiHw+yDoCxa6FWLYXocXGmlpk1FLiV6txaF7jycX0gzdsdIn6Ed/jlncsJjVz5UFqEH+3TthSl/bwfs2ZLG4kjIPESw18QxbvgDniMpHVqHcgT4x1KZF7OAdPs9sHFqKq+VXnmqST65ZIU9kZTo55wSQHq4PJRg7aIE+C/FhNXoXmCzZTWIck6wEE12LkqJiCgwFKYBsHeKJfuFQGJ0pbuzN1JYRs0l5dl2rVRiGnF/j3Faqe/LqlonpavESD03HSfNrvOw6uEDdiGKQdSvwJo5MwazANyLpLc5J5rqdw9YsLnj5ZK+ExkDFdzFmOwf8de9NlJjd6NdnUERp37SuFR7u8MDe+9/I+yNY+eJ9zkmC2+l9XYSyHAI0Qk38vGwevsKEjvdFS0ifZJ8qfO1w4uyRfp+pD739T2wqG6RIGfFuWmlVeHbk0srYLbdyrCh43KdXAJ8E9FfH4bv5PATp3XtDKg8MzXjdWoIHUaejexZNHudMQDNBpJCcs1fn1SnKvzMg==
    postgres-password: AgAOlv+BYT2IOPz+x9n5nJaz89JchIPqb2n1B44x3tAjoSWm0j3UNmYi4Nzbd+IGMy3y3OtxqxI6r/ze3Tj93e82jz6I/Au+3gi6DhEniMy/WAwadNT8w++pccvckhW7NoqX02Qgw3JVDPb4vo4kwNqHhwQSHaCnGhW31R2BOXXc+4vvvJOdqcbmPGrHOyfCkRKocPdMjAveXD93LdU4tUu8YBBNX3QG2kCla8FnXOBqNZU3Z5AsdzagCyWujFoA6vE7jw1NwLYftMsvA/8QmnpXTiicTGxNclQskoyRtkp9IY34l17Z7Ogv5dDmsHgounRdsUztZhVZ4fEqFfF4AxR40EUVUKFE7YLPI5w98Z1cwcfhU7wddZttuR0VKwKaK6t6OKgocVd+ZXXYvMO5Kk19YdkMFLmMEpYNsFPCC0A6soEdslX+T3ff+Clauwa27Wl23jlc5cMahJLeFQ1bez348pQos9kIC6W5Q0RkD61fDD8FVQyNPAOlnOoeSW+NiGXmkU7JbItkEa7uG885GTtAUf9mfeWzY//I0dfOedkim78LqTxSHsOsnXOXdzqBOsPJVsyzoDlZ4Sie2EKcY+1PUtDQxUpFF9dA4Ntbai8kvseoq3lEAjJ7UEF9r74LRPwQzDnM9RSSV9Y4crBkzE5nk/2LNLX3lbKTclswavw8Yu+TBgoACEXNJoKbApeAXrugPJsxuOF+zm+9Zub7ptMObOa59omJS70DCKEEBEHm7w==
  template:
    metadata:
      name: windmill-postgres
      namespace: windmill
