# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-postgres-url
  namespace: windmill
spec:
  encryptedData:
    url: AgCLvk/86vC/SzAr5fO0Y5WBnNN+62Fze26XJzQ8F/jX0fWKVRH2M2SbLOX1O7BpbwwqZpZNcmOK1I8eVJQqhNc0AdCSfyr3MOtvIG07sIFeV1Z4cDjqOKqg6tl9lICVzxvXUcFbMok2Dwa6mED5nadZYmqB9aBQhcOAmErxOzcc0CU8sSEdZ3n7LQCfDXGtXj5aVXy38ydE33FJ7AkqTPZDNsik4DSAmwvqoL+j+UcawyE2EX0WAx8c3ruijEO69VaY7oCOGp+rxjfcTnwNWefcKQqY+WViWd9JWIZiH2IAdAgYdpQx2HK40dkTz2TJ6VxQdp/MrnRrYekjzqSgazDPx0207rAdE6gfNJ4D5nKO+7Kl6Q9V83VtA2GFpKIRWHEFXFgDtrcRb1nKXV/HZHmfuDGmqCCPLvYSdOTW1fbzkEJ2IBb82yPEat/K8OlQFLDPJAXZXj68bpum8/9W/95qyTN9vun9Ecl8Ab36gScz49MYCLBNxvAvb0Iz+Eeo6mMK0GxR6DgwHsHdKlgmEZ9ie65696Bl6mBnb3S2DOPAVPzuS4yb4Cyyqh3C35hVFrdubs4QVHAmX7QgogHY3RpnxS4y7KNvsaryDGK4lTNlsMiI5wrUTENG4eTxhRJwGvT20NnoK+0X5ntOp8dp0xjFS/whXnxAeT6/XzGJIYQq/9iDPGJk5Kt32CJy2ZPMww4TjwrMItLkFtF/7jkAQ1g/g0X/9I8LGnw+70fahKkOKnUd3cgX69bXkhc/f+I/U4WtqVNtxXdbCq1Eo+ox067PwwDVzUtoohizMHsUG5yOuBd6vct8gY0VzVPZr5ggeV38fUIMNFA=
  template:
    metadata:
      name: windmill-postgres-url
      namespace: windmill
