---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: termix
resources:
  - namespace.yaml
  - deployment-termix.yaml
  - deployment-guacd.yaml
  - service-termix.yaml
  - service-guacd.yaml
  - pvc-termix-data.yaml
  - ingressroute-termix.yaml
  - sealedsecret-termix-oidc.yaml
