---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: termix-oidc-secret
  namespace: termix
spec:
  encryptedData:
    client-id: AgBDX/xADt2AvieO0GsrRBeBLQ8hkwMb9doAPXm1SfOa6rqv6ZF9nkT68tHreUIiYxM9GaX54ekXiTv0mf3PzkA2IGCCcCAyJ6Y+cNInv9VOEo+T5uq8x+sO82mbbY+7HMOFhPnZf57NBGM5c3NslG4xI4vBsxmUTpeMjDWCn9al4RvegnwoILrn9NElKaXttRN4j5ZePJxOmM0uAsDskHg+dn4mnJ3qSUqnG8qdFcpBAF0Z6yPjzssyJ8Zwcs/7D9IGMMivNxusghPiOmwjS+p2FRJS+oU5X94BQGtCqAWP5aW2ZTNxD6V06TYqNahEVdcd1OIYzplYBQmz+tAEDlhIQ8KHS2K4hJmoGZEwVXIgX+/GqTmN+AtTLBd+o8bsFchiiC41WIp6B1ttIjKN3BDK/10uM7QdSeYALJct/u4YGp/013yL8EMbTUnT/gFAt10MFKXYLGfwy2gYPHPxr97Qp6lkpdwE625UCfooj+p8Bn8TCcEBHwOORxV4282wZhxtHVBrfJGbVexuZgCvjQfTPoYbkRxdJgm+9YdBEqh40OJqvwlvJWi03W/F13BsiZnnww+1XXiyTul4grxlleF76qcBZzHJKXLnloB4f1vHUqE1I8YEgZQAKeIulaVRw88ZTxOwPXLb6zarxhrweujXLqhmODhREAxA/3aSvKChL8RDqax+agHNNR7UbMiPziId+alWoorU60gqKvRP
    client-secret: AgBN/ZTzFmMkWHKxZPoLGeGwAk+NmChhn8QZIA8w9Pu3Y39RS2eo1D/JdPbMJZFqApGDV6fNY4t/DZgsva5dqmB5mLWAg4s+CX3dLu0amZd8y8hqcHkZus1ES3wJKrzCrxQfIHlz9ZRkCCggK8BBmCX3Tfbkn0F4faxr3WNnshO2RtYLSgdRCJHgmWupIGyo2sjFAR11YMGdNWHhfF0XphT1qSgKXNjmpIh19OLOvR0IPZKPHTGx5LpbSSPpKg/nTveHZFuJKCAgBWVKJYkpxrOE0SbhAl7DVDunZXQk398C8VXraBZ9/s8dxEYSf4Rl19HFIxMbp43dQwXMYlnLnQ32+KSs7GTOLXb15nByuM3ndH1EMyKgd5lAo8lL5lmEudB2oI/++TIp8+LGwQMb/GHd2LNF4Y7IslQen7Xgn3QspBUS3ckKoQPKsPyoJZxKBGE0EoraY4M/0uOUV7hVOg4sZbPVThLFNXQIKMvisKwnS6SFsMmMK8n+NTlQG3Ayo8/CU/HBqiEmSoi5VKdbM5F3EJNiGVvYl3ZI8nXstexLuc74iWadciMq0y/jtwE5oGFbF7jp5ewLyw/3abFYhCI0gBMP4gWtCdPCNyaJ2zJFWJbpoorAnz9AmS2ED6aZYVxE+Vr8a622kg24zx7IRUrPIGu+/RgkFlY6MtyUvi6qMRnxFeEdnDDmkR4nfIYZDXUhT9oCZ/wPj1S+Fx7TIX9Ld6G6yaPh8u1mclBmdn7qV+au2yrj//tUjxRmyZ/s2Ab1mm0+ULtlUT2RSLvNtEs8
  template:
    metadata:
      name: termix-oidc-secret
      namespace: termix
