---
apiVersion: v1
kind: Secret
metadata:
  name: manyfold-oidc
  namespace: manyfold
type: Opaque
data:
  # yamllint disable-line rule:line-length
  client-secret: NmJlYTdjOGFmNzY3OWNkMzRlODU5OWJlMTU2MWJjOTllZDQ5MDFkNjhjOTBjMWFiZWYxYzNjODI1NDA5MmJhNw==
