---
apiVersion: v1
kind: Secret
metadata:
  name: manyfold-secret-key
  namespace: manyfold
type: Opaque
data:
  # yamllint disable-line rule:line-length
  secret-key-base: ZThlMWQ2NmYzMjA5NGZmMzZhMGMxMzgzN2JlYmMwYTAxZWI4YmU2MDFiOTFmNGI4ZTI5YjViYzBkNmNkNzQzZTMwYmRiZDRkZWVmYjU2NWY4MDZlNWY3Y2Y4OGJmNzhhZWQ0ZDhiZmUwYTIyN2EwYzM2NDNjZjM2NDk0Y2M1Mzc=
