---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-oidc
  namespace: warpgate
spec:
  encryptedData:
    client-secret: AgCMLUdXa6QMLg93VKZ/du7VndMfc6CRPJW2J9MPi0jh2Q3W8IHjaCHs44SapX1n02wrfGIoas45TwricmXwbyIzCmGfLnp6epdqODZlmI8nu++1hyfaS1Sxt/xzdBpxwTCyaA8DRDabjh9zP0ZjsZv/egA5wcLZeQd2AbjkI/llsrxs7PqSESC0hENgmet49y+jOM4vdxxFAmhxPCZ0TlkAqF+DlRozs9qKkI0/J8OeSW9Ht0YFoorkKJEMJfccP0g+4VU21e+SyoesMfjv+m/prtOLM05E/StW/FnlYXeFhzK9o8TT8PpwsIeB1WcVFBOuZtB6YNQsBNCJ2L7ITiNm2ybVYWO/XyFNjl1uB6h5qgmP8k7NGq1zZFLJJFR6pPg6PBQqaOzgJYRnGDY1NILErPOemy9bsh8u7+juwKlaYIkljhT5AfrKbM8zEy2o2NlG4LYkVdWW7U95UU4x1/6CYbqjaoTetgq2VXZuk7ZckDgMBoEPWfteRTI7t22kabAUBq+mtk3/wRJBP+kbHZ2M+navHIf8rCCvRrS0TPdP3aMbMc6pdKg555ILHCgbEI9hpMgQynEUiJAANj3P5Fptc35nLPS1SN2S0h4jGxXxlwWs/Cj9a3NcwoCdlNukP3Xd1bcQbkRK9VN1FiaLiN4u3m2cQB90PTO1zoAFPpanFRyuK2VYP+3yUYTAY3+/QEdF5OIb9ZR13My2/zucXmKWZU9drYzoeauWXyWc363gkOuaOblp/TfpkVcSII+EILc=
  template:
    metadata:
      name: warpgate-oidc
      namespace: warpgate
