---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-oidc
  namespace: warpgate
spec:
  encryptedData:
    client-secret: AgBu+4f4IgXGQFdcuvkheV2F3fdMl7KHJQhbfaP/d/Krfus2mKlEpA8xe/m5sMkCSNGIbrjp2UdZjc5voh1vjUCmrKYlBVKGO3Wx8/XudNBVdp/rYUm1qfVOFDlrbR97UHgt3oTi32kcL8U1LGludd6VA9RzhB/zCEUPRDLGv3WZ796CfzMWLj1NXbfJwVcyduxqR3y0kn48QGIRw9619bRcqPRTNtMv5pslDEwyTpHRK1a4U/ogm7Lx86Wjg2eSbe2/e6ZrsOthQqfcqbc/mSCpUF1l2Xis5+x0rsHjNOyuVvU9iBemaqHJfyUFgsc8W07LW9UvSJxL6KBHGtIsYeOBpvkmi0okoRfJfWe7mcwki5diKGeFCh8I86AyZ876xZSfXwzYmZ/v3ZXXL2XxeuBhzBCCtSg9DMzIXh+qyhTPqSkqVNC+A+CCXyaKh8Vgg2gHxOeeNkkTgGVwqfEwJIwbc6I+1kGfZ9gFF9EKacOG3Yth98zrPMRhoqn2nRQQTzLOFfWAdiIEMZv8ho/scYtxUYdJGFaax8m4zgBhNZ9hpt+sd96YB6TTdxjIVA0motJtGT4fVCciRP8Rz00AVSUSp+vPiw2gmAX/o6r6M4oqALROzSvPpEIPuv+0kOCAj03dZzarsIiejCoNKJV66SI4lWJ8SFdtt3LJdX+cOS274I0o1ULnyjkOycbWS8J2sQ6nG+2tyHXDqQ5rlW4mC4GuB5Ewpmjf79vwfPZT+YTrh7/V5q8J5/LeIpyR3E+w66YJMXEGAGWqEGjd3aIyOYTW
  template:
    metadata:
      name: warpgate-oidc
      namespace: warpgate
