---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-secret
  namespace: warpgate
spec:
  encryptedData:
    adminPassword: AgCFdS/wM8+ye/5ek8iexqjADUlKkmQcS7hFEzgyAELlVUtd9fcN7Kx0pyjM7x9e0s4y27+gLMh8nChoXKB4wJXxE5Rl+O+/puZCrgiyeChHb9kshyyKdc21+eoMo5wXc0XxKMPTquvtqTyhJf40/s/05+SkQW0CrfDVw6sIjk8D8cqcAgWnJ3hXHfpluDc19eJnUXZ3lBSjTIooDL6uLS9IY9THZMd0yLDUk4CSJvJnRJLwkAXGNS6HSFDl33OmK52oBH8v0wpwxtAFd68AYZSZTHqsv6gE8XJLhyODVb6awsp83aPjUOZNPvM1M4kvb/enNtWtfm4O8anrXZ4FuT41EuS/4HDxgERuqacvXsX2uiism86HQ3Oes57ztQsPrEpAZV4EvWXVtwu+A1Y3RkXX7WeSo3MTR8D69qz4QMyqImWDo05bJnl5A+/v0Ch6FewbWa2xh5UGFiYQiHPAZ0rHVG3lhlW23xsN3cvRpGFNFt+wp5r1jZM+Hmk8lczfUicDw4iBXOVQhyRpBt3bAYWHWIpd8gGd6py+JaYopRcuVdFhSEhpAs70GOH+0FIYd4iM5jju4cAskCXNaHC0Nfm1iQcVztx2p9/eeQI9eS3Rc2m9dN6tTqlpRNOEn29LGcsR6+oK3AAm2mAqN2Hoa01ViYHhWELDXP0ZhS8qWLBKlkbv9nSZ/OItzsbqHyqvtTBxWTYXXi59j2FTlJGSVQ7UrvBVLHqTCcPkKDtpHinmvyb9K6BqC1u8dHiA5Q==
  template:
    metadata:
      name: warpgate-secret
      namespace: warpgate
