---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-oidc
  namespace: warpgate
spec:
  encryptedData:
    client-secret: AgB9HOnhrzgPpui6lxv3eM5zWZw5tDABwRuhNrQjV+E3fbulkmVmHSuRN09FRdclnCAKUB4dEWb5ue4qCbHGCUAxrhiOZe75mhDWjHVoolJU7uIzqao3VgOdi/YSVzzeu2U2mHnOaikZipEitHFMcNRwKmp8kyxeF9H6fSuKq0zH2iAoYBacrD45CqTwRBwTVZeEJa7Ew6MRIpdv7uufFlKb6lj/PTjh1ywPJF09APry42PhFHhMMwtop4t8AFGWP1uZA5UlV5ILDpl9YMoq93HWUIuHm6Nhx8LWRSKCQ86t0aqbIfuox84W+VVr2PNF7N6/xQp9xRNY/f8LoVot0/hXJsqSCTfVTDleSWmK8GufT7FdsDijQyPBg165jiLsO3cDC+5ivxzHXlxbUnLzWCYhdLSQLH1wVAHcifsRPsWhmJMtBHwup86NTWt9V4JXQTmiOMuVLIZdPz6PZCdj26XzRO3TqTqE/CnBOWpu7v2EChuz4zu6HZnzqXvSuyGd/vw+mEQhhG+sid2D9fU/u6Ug+w60L7GHBAG4it/tF9/SgAQSo+UN7kDyAcNLMY7mH4UKmSZDOmynT+sJCD8E9TZDEKG6SiufofzVOXFFgXj1zZUsrFP3xF55V/lmYF9AkbyrR17ByLgUOYzgT+hpGkEknccWblInGQkLlzaCfRn56UzkMYsKPGhSeJy3vAul9BFp32Js2iSom3eazKvDqMHzqAiUpOwpg7l5RosSLujbXjQqewZvv8mZ
  template:
    metadata:
      name: warpgate-oidc
      namespace: warpgate
