# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-oauth
  namespace: windmill
spec:
  encryptedData:
    oauth-json-base64: AgAPWrHGOhssJ4mOnN3le6tJp6nJcia/CkK5DiBDq4W/xzNwqHWAdFgbPv7aCF8z6jRkQ4PVSZwsgJMzvS7NIQl8VKUMUbRxd91DUDB6YiWj+NTovhgtt3oh5rhbw7LXC2/rKYYqiSgG88U/tDJ30IBJutXl4VFd6RNMlT8fkkZAOoH4zC8x2nqlfvnr2lr+lxbo5S7bWdjn8EeSMrIqvs9rUknCHvBfc9gmVslfpXa/h7QDNt8GFz5h+5yO8NH1wrX65m5Ku/MdeKcIESdZD32tcb35tZpp0p2dOzH1qflO7EVdayih6GNvZYF276SszBnpWK6WWpV5NMTLmOEVlLq/5pFaHt2+ObicmyhJURpt8SgkwS0Or1VvkwWhv5L+pARqKn7pfOu7KPLQyYP1hz1PHk7xjtTApK7DXk2pB/1Uz3J3sgYxKl4wx06Xc63SxzEGIWzufx7zuaiPVBiXral3hOzkAVgpzIS0Q14L3G+Y4PFfC7+u3GVKtExQBUhUk50fSWkaD0lkuVIao2CBWuyFeIMeJYWHUzxlIJqjeq7rx9CzMB2mK5Myb7fu5MdnEWkgpnQTaMGNn8v+t0GJylYH81rp7syggGUO3mZ4XCGTdWxnQuRtXswsWgloiHKy+w/iX9SFU+Xe9QMU2Ll+GwL16AD2irsJwiHlzDK29MupxPnEshsU/p0axv8501eHTfZAF//Y4aOhlc6cmhHwtfllsobn3X9gBgS4FrwXpXT/Y0ruwJRny0qXX52ksOVk0ndzzrManLFL6tNP/FOlM7CNpGwQIRVXKnxaeOjEi49CuTCEqfiK3T3yQ5q5JYvjfbZ2G18MiHgBSknrSSPyA7pbz2oU2QboUCqkfCtepuKXKLKll5KTLmTvVWKZqViUwCLKlYLlj0bMbuhBqPN0jc+ZrJGvIBlBoJBzUE14HFr0O8WJzDCcbyaNgmzHHRS3GgB9yoRR8EN7VAdYklv7ca/G1v0LZusV0wZIfy5iGqrHKElqx6/IeFrNmpFbCw9SFkXkkxymODJmCOkLf/J53jAttcjK5X+hA3yn9d4aC4hyVlS5noaxWB8/gFkpayJLAGrAtecsBHzq8weImMGNubuGpzzxm2pYkA16wZpNAHITdHBaar9v7xLFcFO1bGWHRlvRIBRO9g/4KpUDMBJsA3D1sIVihzbIJhZ+yUzXtIKihV/ZPGU1qYT1tHBe7qtqrObI5WOI8c+dxrmsYGSfjhnGj1HpyccX84t0oVVzDPvclwxieRhwvkwf5hhoH0waJ5Q=
  template:
    metadata:
      name: windmill-oauth
      namespace: windmill
