# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-oauth
  namespace: windmill
spec:
  encryptedData:
    oauth-json-base64: AgAFUGPDRFMgEvXWEmZtt9vCW9toXgmKAkUuegNf6+deyamur664LXp/dY8qmykp3hfxmkx5gCHyTgevLvaeKqPUqNmTwCxuYxtxeBfDlnPA0UoqGEp+FkmLoaq8Yniy5xpRQYpYy/ODQpCArhEZbQlNeiwbyHmPx0rhPXZFTFMOpLqYvam7HqWbV2/Du/hU3Ex2BMAR0o1Jw2pb10vh2lrwsYcsJaWBjbrIfp0DeHWx9Hevq2EL7hfexQjHBHjwWn18pi80IfzEmaFGQ+9VVtgCiT//52JPsU81r2+nuneSaI+bP9+ndX4GMq/uhuHTDz7J/Bsm6IdIRp6Ou0iusQ36IbpctDxE6gMGZOhcXB97iziWcQXDAXBxoLnWbR3lTzlOkJvp7WDlWqE67dbok3XXGyTAuKLWTRL7T371/3s8MPWfqRfN4t1QiLd8Q1WZgpLHsqGYwPrVU5HtvW9VBAArDLH2qljfvFOSijLz3W+yaWEiovkIwa2gUMqYYpXxkRQRHgqUCUUFzEdNdZzt8rcdXA9Q7JMoyErZdhaplEit215OlrDggVbFHPtJkjoiY6tsRzd1HuNNJnn+/NatnG/NxfnX5w4ddhGWIAxhzwQhZrQ+tsjlMq5QlQl9CFrWB2i8UU32l0E9wuqG5frZOAZYU0h5vHLXXZB0YOo1ZPLQ7F74eLswIXs5xIjB+EVDeiiETDGih5NyTm3a4z78xntIAz2W6dIBs0n7M6W6ZmrL4b9DwAVQL4kM3H6RNB4cz4Jcx4cDL99KEgT8BTDCR5WUmAXL+iqLsTJhL+WYX6b/ZtWrY+0mLcgqfB9JVMEErxwMqz/x15F0Qe03z3ubsFMrzEzf6u4Trb2qB/ud9XQR7qAF4H6qzw9wfy2eDb0t/TtTwdMCnr4Q7VnnlPpRdpnEa+wUCg0gQKQrMayWOJuYl9Pt1rgguUQYELu4dJ0Jvx4Wd53skewiwWW2Wb29WAZgUlw41/S4qQfppYhtqkIYPLEfOd/gxREBd0WExC+9rw565x7ePFoq0jW8524NMSEsxkWih8O88jhlBLTj87C/6IGaiXKWK0QEBiwoXUcRL2+GSeegti7XKU0e/9HJ18DwrV6f1LLoOfpJvGCBuSDwnzaFa87wUl9kw1RTc5oyVrMPNy+FZ6ej7TmvEbx/MoF1i5VPohI/treuHq51NljlKCy7uBsryRXH8QvcCulKhGnWj2SbOik4jf1yoUoR+me0AV+yuyDboACOyE3IsJVDKpmyBDbKXcBAyO0GlhS+ez2FuhbCJvGBYS+rWx46O13G/7N6fA==
  template:
    metadata:
      name: windmill-oauth
      namespace: windmill
