# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-oauth
  namespace: windmill
spec:
  encryptedData:
    oauth-json-base64: AgCgwP24+koceL7qLhNkv4NrkmAgIwV4ngQ/JJGtXDZn3g9+W5rIOqcb1hqCyRjpa1jj6W1xYobRpRNzFzFsNjW5yU66wXiEk2CZwaigPYGXPvRbDAil3GG+QRQ1cww5mvguVNFDmTAmdsx2ZLFwl2yEl5k4qox5ux69mjFzYbVFD0Bk8q+SfLPXZJhQ+FCMhNcNFBCJdio9PYlKBJBfyMgq+J/HbFG/a8ZxbkxfhKWQzbkwYUu5oY6BYGBZPh1rSl90e7Ckjiw4BLxbNVfpZSNNMEqqHXhhLecQDfAIGoJi/X4FdCRkgcn5hvaOMdAOAwX+RlMD2VnGzl9SjZX5UbbpGjPdwcwQPezYNY3JwB4BK904ZzLSWuCfvUDf/B9wq6hm0j7TD26ZLDg1wVZBoUyO5pP7N/OEM3G3JgzTfiwm7kB2EgU6jD/g0yJmAhIkGV5WCGaxS9gcl25EbHiXjTOPShULRUB4uOWqK6upgTFD3CeY+kVE1PbPF5C0lchoQf5BYZ8mSOQjrrluCNcGG+QNeO8+ou5/bWFrk27HZ9IZ1nNWGFFGpcbR8LCylACu61Z6x7QQPqO3RyWnmuwRNQsLq53JdDATqZiqudcgzYZDF6xzsp68Qr4frBzMRiNN2xXD6l4hzvkSnHr+MlOLUCO2r+X4DyXG7nOmCNzH8SPt9dwahcQSdDJuLFcMygQbjHKBz38AxSIk2Z4e1bcSo+ojQFfBTGUegoGcz8se1+mWWLZP1hHPVLf672Z6M69zw9rNKCQQQZestS4OVET0pGQSey+7qM+ZmO8MJ40DrIPJlv9zdik0Xxzq6iLrGvF9ip9VAKiXFGI1XoyQAS/Q2E3BUy/Q/UfmsiIGI/zfMKe385EEpYYZsJp2+u3juKAFuyXFAAabF7RhJopF3D/dHahNPGnY5YLE4qZxDO13eF+LudzQwTM7idFcqsZEWBTRdugjyFKo7E0lDBOvd8gK/7De3WvB98WnO50gtQSt4ba7spCU+F3EA3lYRBQX9rdElFhe7HOR74rbffy7XPa4sSUbd40NBNMYcWwhyUk1VFO/0Fj7bnqwhUQSQeocb2CxGFxkVwgYMFUyUC8EnfxiMxPZ3uoqDX/uJlKWzAgKBPjTdEblul+gGINywhLjSiYAbjnSOSLr0wx32adHVMdXOUjUr2a3IsHF4svLPMclsDylK+EDBgNQ1EVsiEyOdZYLT6YsgkAxWA2QPIS+LzIJ2BI1eAJZ7ohwfs/s23ewhO3svDP5bT8=
  template:
    metadata:
      name: windmill-oauth
      namespace: windmill
