---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: loki
spec:
  storageClassName: ""
  volumeName: loki-data-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
