---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: loki
  labels:
    app: loki
spec:
  selector:
    matchLabels:
      app: loki
  namespaceSelector:
    matchNames:
      - loki
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
