---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hermes-k
  namespace: hermes-k
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hermes-k.xrs444.net`) && PathPrefix(`/v1`)
      kind: Rule
      services:
        - name: hermes-k
          port: 8642
    - match: Host(`hermes-k.xrs444.net`)
      kind: Rule
      services:
        - name: hermes-k
          port: 9119
  tls:
    secretName: letsencrypt-wildcard-cert-xrs444.net
