---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-firewalla-credentials
  namespace: mcp-gateway
spec:
  encryptedData:
    msp-token: AgBm58rZw2sLaX/ZSGJM6K6XhaUeWtfUz6p8bTtsAI3c0WbpN9T9eKKvPzfrWXKGtBOrghZdsaqDKOuyDczN3voXx1xOFksftBze4/XdRgXMMI7RxMvlp6qu0Jsz79dSwWMc9OrSTC5oqKU0gVcYrLZ7URNkShkqbVj+EFP4b2NXwVwDiCcaU9VHQyRG6Mr/wTyxbD67AwTZ8vWW2herwJjO2sNpnLMF05SXTt3B+hK4RzPFh2Wa/9AKG+ogkjxGeHda4IMhMcYHrpnIQmj6/yK+6JcpyWxEYT4sES6eCQiCMgSI/CcNg+bvi6Q4CHzpoUY1ajAlNl53pmQ5pogmd9l7gH5Zd0COVE/EzvXaAEjGSVG66cjNkRhngxDzP8WLVXnVmh4X55Vz4SHna/a0Vtf7v0VRTgNhQkawDxP3mzHK733a6rUW7Zvrb02EQN4C+yHyDxcegRzVfHPaoK5ZgK88BfS/2IvGJULStQ7b9L3z92UZf+Ty2jHnI9rxL5fPPc98jmgos8DbIMuBus9UMQUzXm2JEH+HqeqZAfqDjod9bKPlWeqod5I/pA26UogDyiR2MNmDwxBhEUwoCUJY2CN+qEDopRClQdz1OORmpTJ/wIwT/wrKyVUY6M72qcl1PxVwl3xyeqQycit6KsI2nXmGV/xaxnMoDkP45CzdQK+dz08ljVAdr2W+Je5f1jDnYD9QxeMnTuCljKKVGcQ7C4Y05d51tZe2hSYL65Qu/Ql/Pg==
  template:
    metadata:
      name: mcp-firewalla-credentials
      namespace: mcp-gateway
