---
apiVersion: v1
kind: Service
metadata:
  name: mcpjungle
  namespace: mcp-gateway
spec:
  selector:
    app: mcpjungle
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
