---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-ingest
  namespace: manyfold
spec:
  storageClassName: ""
  volumeName: manyfold-ingest-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
