---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: manyfold-db-password
  namespace: manyfold
spec:
  encryptedData:
    password: AgBkG/pmc44QzEcL1NbTsB9VfTYLvMzcvIyc5LUTIT07V7kOqydbPnQ9WtNHl5Y8/gIwattoyWECuGSFD8Mu/ouBqQ2bRRQq1zFNMN4nFp/jVM1qL4dDnQanD5ZSKAb4CL4+nr8gAv5le4gQayYf49Kglg9gjJRQBCRIPgLARW75fWVpOSfUfLtPNY0JZoziLJxy9Sn7QcX53TvEZvyrEEt99RAK1zyeBd99zTiq8o93kKD6IpjOy7qsCGNggUtDBffRn8Zk14wspjlFHwCGcEScSv0TmH4ow8WQLGp0UMICufIS1nDLXy3BRwd0DG7M0dGBWik3cP4AofkVK+CKMYUpkBWFomJng+cCEC84/SKIGRoMQYta6wLXsWFJKNzrTa3oqPapKl531RSr4XtA91wTgitU5syHyAHYsHUNLPDqP/WMOj4rl780flEiGfS21vCrR7VBOQIABOh2TLJ/w6Lip7Mm4hvtS4jjijUXBsEhe7krOkK37ONR/EdFP438900BL2dZvYkxUeWSUF8+4rugScvLicVdPsNi+1b0NJV6oKeh3wY6cpnlYWhESAuGSHU+E5VN3e+oT0NY5Qg+EgKqZfNzFJzFff7bBftw3Nc4O2BE2ncnfB4Pd66bhvaQ74VO4FYV9/IedyB5qjKYGAVFdWgPynfqjJ4wjfAQ95MCY6Jc7dkPhIGlR+UVcgf9Hlilh3yWZlQXcbQ0a48kDcyyBDxrSpsOWR6NjqyhTbdnAzI2xF//TCqTh3he+w==
  template:
    metadata:
      name: manyfold-db-password
      namespace: manyfold
