---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: manyfold-oidc
  namespace: manyfold
spec:
  encryptedData:
    client-secret: AgB/XkRiyP/TISnozeSjFFqyA55Yg5r/xwsfDsw8fKzgFRwN1mI4lTdiZOxLPblD4Mq9EinARgLmwGL5IeG62+PLWzPfdx0++1Hj05hZrCeEUQfAD87LrFgI2YOq8BYmGXH/vC1dD9yZ4EF/R1o1jNF9AAw0DKoJdyJvP7GsElfqxBqnjcNixgNpREQs9GqL0tOESSFwKC0CNd+JC6WI0293ipFggNR0XehS+HMPi4sS7qNSv9o3fGdOiKgFO9HHv52Mird8QGajA8TDMPZJB0z42pquNnvgQEG2nKxO6Q6mpLPYNjy+R+L22cM86ebjL6hSRCqEpVBpBE0XebWcTGjUczlc6b/Pl5J+Vqprt/arBISAXXTv5begQUanbjJglugovFjvXp6kSy5Em85djHFRjMhP20LakqcYghtp6WjU7bYxrQKhD1hYXuZuWJWQD0MdNeERPoXKjgrNGK2P2Mguv3SlPktZeT43WwcmrVaO7XDMMd87lLo2Cbk9DayY0eV0zpod3QhR0RVpmHrJiiAK7vUvQMM3aWwFtf0mHXTzd0JOOUJz0HcAfrPiI+2Xh7KYRiIlQacFfeGkssNuViQASG/13ixpJNDsivoTuxTau7bjmLAi9sooynhseRxXyq5LNgY6zbroCQzOV2sRIyEKwYdrqN+mUn9+9vUGpL3n8Fu1QfyBJBaoMkZBcwDHEAipkzbhJduRt3tbWoTt1XfaPnU/FT6Au2PySmI+7DqIAoTt9q3rtd5YVWvo+1NsNB2/3zf0vTGWhqzgzXGpJRb8
  template:
    metadata:
      name: manyfold-oidc
      namespace: manyfold
