---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: manyfold-secret-key
  namespace: manyfold
spec:
  encryptedData:
    secret-key-base: AgA1P2qzgCiWJLPOiP80eUKx2TeCTDFcM6ZVrfpQBRHyHlnXM/B2v+9AugMCGbu9KsJr/IV6wTbV6BZDDsz8WjVcehKuqSXkWOfagDcytWlXUfTXFxzk7oDeusFVhJZ5bYz0MMV4+wUQN/cjAk6aftjHcbH875REIaUn4bu7oCkTvqUmKuGwiQeLh2rBe9g/nKxeAAh2VLROcft9cjtS5I3+s7u5+qlMUYz71Mr9b8/i/1oq8SdsOQ6TJF01Lh+Ww/ZV/u8cXIUD1nktcyTax9d2v8RtzUAB9eZNGGrcx0+k7DnCSjoFAULa5wio4ixBhmiYQxFzUwEcS9QtWCZOnP42t+yDxKeAuTI1s5dG5othp0eiqRpTQ3acbl0/ROcV06QabcyCULmV1RCwDRUx08WcQf+KeSq740u3VKnIOFflPD7GtZnyf2i8KCYX3YF5Gnkf3fXYvSCC3VnQf6NDZMTWZYs125IiFXz86hvKATI6KZ7RKtJtTxNNrURE7tY3UXfK0VpcLOkPEyaSiRUrtXDrLT/OzEthZ7lc3Ok1QPesWhpoqU4G+cFBM8addHtPoxlBB/ZtspH98xmjPCxJkQ8TC5XFF8Qq4fzczjikJZpyWephHzgMkgei/U7UE/6g16XQhZp6b4DhfiI4BfhjHz+1FXojytn/JBf3K75YhtEkyCcUVxzYRgb1pbtA3eJzGZ8CrXVtTe4dhgWSa7e3upL/C1ULsGA50oPz6D7NDBwYwW862jCx8oU8+QPlorMfjFrmUIlcXWIjqn5wvLEjLAA/1mE9pFXwyL8lYkWgNdgIvSA8k10UQBz2gDxgaT31q9I6p1YWn446mWYGKKTsOC/Vsw4RkDZhYPz+XOQPlvkM8Q==
  template:
    metadata:
      name: manyfold-secret-key
      namespace: manyfold
