# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hindsight-config
  namespace: hindsight
spec:
  encryptedData:
    DEEPSEEK_API_KEY: AgBfxoKH89M9+pfJNcNUfguU0LZ/ulrPU0Y+6FuxTBlmnsF+3PNX/a5O2iSaq9GoXUsWG3nkg023vLkVY9Or3rvhdab0NZkKHVRRmQoc8e338RyeGrg0sRHE7RommDjc7ZTQd7la82FyTAvDdw8/HSsaYI367D4YZSTdvdSgy8fvPfqakFMoUvpPDpMUCS0RmIwZGnHa5blBIUeYknjbQQC85dAXbumIqr4CChFjHuYpZQskiP4PicORawBguBp0CM53mWTdtg9+9lQqQ91rTIZvIE/jjHXAxYLkS26GEVnNRbZvcOKc14ltf46iekajhEr0T6pV4DOH98hZWUl+0ProqYAdZrnmkXzAAYrk52AMGtmaU0nwxWtHFHUDq/kI6ppg//C9XWgmgvFJgl86LuqaxTVda8hq6QYO76L/cxf8BlTcRk9Q+Hqm+AF6M5wY0Rkk3HsGFUC4e4ArNnUDFxvQAWxxvjhx4b0xILsB6ANE1D2Yvy9TWhVniflBFsdLemN+YDapme2EdjhoSXTuoH6am0FtsMA3bBmRMzFPhqNT6LnL0In44HfIAPWDgDpRWuYksJWmytNieTsBIXzOTm4OhJEu5kRNQcr3KJY4bTTR+SwRmCZcNWFvFMCl4jpgVJEoPaaxljgbOX91GWuT8LWrJjEGDSwG/emW9Wl0A4PySPF+CSG5IEvJxpX8BAxjE8OBy2xgToCoIfPYaL9BJyMn9seBGQggOkq/pDamKSyBO6rpbw==
  template:
    metadata:
      name: hindsight-config
      namespace: hindsight
