---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: radicale
  labels:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
