---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radicale-users
  namespace: radicale
spec:
  encryptedData:
    users: AgBgj7RHf+0tN3duu6j5xJdMNSfMnyGnkZtFcj3UW+Uh2kFssYW0QfGR/tosfnQgwKakob386KHQojTqy1YAZotnifKmN+w3bd3NJYtiTVz+BIMj34sIeCREIj1ro30mxSOPanAO2vGsHPBe5xEnZzsPlL35waNxeY3G7q8fiB9kAdsgpboDHREithMXxJwCUckbDMUx1c5rxN8MWaLriSgM2upr+p61fwl4Bbb3Vz1ndgyJ0kcLhol3dbQvFoVV31WmaRiX8uwbnQ9j0dpQIhYBSA7RTfSz0fRDTdhs+WOnxWmQrfJSepVJTvyX4l7UsvPTX17oyrX799RnIah1avhhs+k+9qpepLMGXLEcskQSm2bRGWNYkn1NguiFfwXbdBllJWn592bZM5UiOmiacjCgyx07XAfmQNQweVMfHW3oLu/M9mP5K6vJtlRIZJjz8gj6qO4D094IAwYGO6I6oVh6kqph5DBMUXt4rGtMAl1gEn9inFvKKLrRNqL3zbUxUk0TB50P/YD26vuTZ0BsotSMk4D9I6yXT7H79q4+N6KANKEzE5obV4JtTJOWc+ZJWJd5niM7sCabb2BuLYHPx5VFJrWtOilxKE8wMPAxKY8jCpvoSoUbgr1vev0nxa3VZAQU6u9CF7c6tdl8+z8dhTRJzd/5LpCsfTMRatnabPqMpCu8X4QK1VC8ZRNsTCs0HBxYdiy2RGhPO5E9Oo8sXrU2Xjlqhf/L1TkaJLwkbbIwM5H1cogS/Y+afVkNC3YS/G4fEXee4/gcGDXweDPYGQ8XO0SRA/eOaABKVsvaWqrOpn1fsKzYifJAKmHArBOLcBUEPiU2u8dLpmS1BvaOtTLVGNnGe169VkkoTmGYWHMwbbXKySfXmeNcZnnLM2Ed2IRzGUuZ+xgLN4fUTZA5lQc2uwx3IGvsuQd7Fiobrug8owDT70NJLYZ7Ar3XcgW8Pf1u6roMn4c4h1e77TFHxeiAIeaFLB9BiAaaJyHox39MAaWww4nVG7U5XClKrYt4ztfYKaQLisc4/2rb5kPHz7D2GnbxPc9d86V9DGkNFz/o6x17
  template:
    metadata:
      name: radicale-users
      namespace: radicale
