---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seatable-mariadb-data
  namespace: seatable
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
