---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-apikey
  namespace: sonarr
spec:
  encryptedData:
    apikey: AgDCn5iJtxyHvHc1zIQtkdbmDyLnQsjpaGVnZcIaH1Bklo7kigPB8R7KcQLQkMsgpa3C2Asb5pXydX/MXwBQgeAv3IrUlvoj/DDHL2lKBDmqDJAXlkrm1dE4xxV6ChDtgTMVwfsm0s0Mdi8VY8EBkCoIG3KOuqMr1eCf+MJTtn61jiA5Wd20ljVZhfB1uR4w7lo73YsuM7mVtoEB+QZrJHHzV4I6ev+mJeKC3+i6pgOj+sNeaxCXHC1rBbulKBuZTNgYF5Jqi87YUklBWsjrU8Jgnw6HRpFSSqnXvd1Qi07bRvbZqAmbiIVZ5qyihqTTkLHKvpQn5YBsMECBuf7WFONnriJU4c01IYM10pfY/qZKgXAkmtxxkz1jdqq9yYo48Cl5UlG4x6dfuRLCtZf4EILeZDGJrDGP9asKZHzCerevm1czwbrDwJur2e1ye3AmZN+j2SieutLmGPE/dsDJIgfJ53T2HMHC7EQkkytgdmn3A/74yN/I8R+BIRlGIg1HcYYn3ydG8JWfx/VJsdHP6dCZY5Bp7SzX7KKWUzm5DvhC9sCuZsKPsnMUaTXljhhxK8LwFP58+r0w5Ix3A+zgkWmfi21fTtaZjY7Y48qS35oAnKZa8JiYEJ6k7H4Pm2StS++rY0yKnLGqFzQh0Z0y1cWaOL2tix2v4tLsM8ZFHVCaGYdrXDXJ4pGegr0Ph9RJCRDMjkwcaZUjetixHD9wbs823JxBarTTlT5TPx4guMaYIg==
  template:
    metadata:
      name: sonarr-apikey
      namespace: sonarr
    type: Opaque
