---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - sonarr
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
