---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-personal-s
  namespace: mcp-personal
spec:
  encryptedData:
    CALDAV_PASSWORD: AgBcfrRK9o3as5J/yuR1sFudSgnfOlZaGTLYE99xqHEvM24iCC4roaM6ReCYDJRz6hHOclDNGVqz90M5LCoSvGHQP2D1XMFzUR7JzbYWtZObj3Ya4HdSk5uS/GHoEvyWKiO2Hd5rQ6EHMY6uen+CiJ8DFuK09s1lqClrcCCmfE9FdQShJKUXlP+tqmrzwL7UUMbYqeNw7ridNu/kc50HmckTKo9BG9uuQooHeuCMk70PT0evWxBS54V3pDaHy6wCYZiHkOVKY0MEtAtdltXlIOIH/KboUz/YvjdAHz1pzUxvNrZANh7taz63VUprhuLLlgg40kTGmdLc18oJR6lyx9IMwgwYokvUNhc6M87b4Kk55vGlTN7BJUsucWFSI/2JrREyUYfxrlomF5RIv8WlsVy4Yk9rQJXe8OaabZjZs8oKrN7OPjb/DeMyC/gW8a5MH3iivVEg4djQiSpEbSrsvX2oQm+u4AWkp+tof4gQHyweejOHpcksFYoHwluT8ZD9VRyTfeMvvTlWbClJn5gwSrvDMo5ugHJbZxsdeUsTEyrPxdR7Hq5CTo27cVdbYepU5AXUrICr6r7A7TC7Fbt5+qwCAAwY+wYGdDX7mN4n1CuSJ+mWYD1eyXNnauxuVfgX2xZ9BhPgocCo8fIahGTmnivTCFN1ONyAqRLlgjWaG1tzx9cGu1sptR1qL/L0S6puJty0bwIxRfJzGenb3hkZBIFyamGnm7rH5MKFIfarb7LuIA==
    VIKUNJA_API_TOKEN: AgDDyqctp4+KZfxChaiTqggT2BX38lgFKwvMclz4KjHUi87RFBUpkRhaMc1W224QFWZKZARM5VqgEDWMBLuBgeDU17tSIsBM+SEL6O8QGODlKQW2+v5RLp7bhBkP4/18ebgUws2PCIKGUWqDoTge0SXHRh4Ol+LE3tEBat/BowC4VMbnBv697pzGRgbKMs7G0EhamBlqA4/mludMFqKM60FXdFUEbSZ49vwjWnOqQuF8UD0BnKb4cMt2EnaZQeXeW/uBNQB74Tp94XvCUXDaWvsEDqStzVCmGaHLBzUI0MkHFWgWxQDVCZaoqNkwBs2PzaJ3U6DE1jtk0p99k9f9URD1oA1BVlrUXuOEoY8RhFYg1vn7IMjCDLasBUtMo0F219BtoTOmzJkpdSamDjJ32XQWkThPuL2jXVzDuBYc4pLKXt59eUxDHtsZX/CLdq/QhkR+OgIk5Fmjpr/DJZ920GvdV00P4+qpKK/seNh9cBKTLKZ1V78HCPHsNS8eQR66JONTpbwI+WE23tlNf40X+GEeCdVHg9gX6bsSfh8rWmk2DLnzHx0jopX+7y7k3N+hx87ufHtAOivQEDmtYTHkDdGUz6FYDwJ9iCZLQaCadNlBtWN4lrE5gxS0K2XXvB595j9zEuZ3JQRKsAaUa0hVMtY0eJxqqaXAaNCF+qJn6L3f01n+uO8eGBJnnRwwn3NCBN6XUzlMeLZFvWZpLUS+vnHAtxaP2aogMScux1SvMJIfrVZe1SGU7dsef1gh
  template:
    metadata:
      name: mcp-personal-s
      namespace: mcp-personal
