---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-personal-t
  namespace: mcp-personal
spec:
  encryptedData:
    CALDAV_PASSWORD: AgDFzp4RQmtGo3S9mgU2Pv/SsGaciGyroPKJEyAEswhMa04x5OfhOJaz+ffEMSxiUwUWe9PbfO8Jtx7tdvQM5A0P/9Rw+XevTJGsvjqQ8N6LmM93jPO+PoLGD+7io/Ch/R/CWWro4pjGClQORJeAymPIAIdp48v+GedUC11CqWvLbzsSHPJP8nBUnKcfFlLje2Mp5nwtB9DCiT5m+X4gH+SvNFfEEm50Rj0am+tkVBwg0WkccQLqFEZlzgLvKSPlvY4kpJgNS8vpCATf4pHjSn3D5bFv772YyfzmA1RldRlPD/1C45vhdEKF1EAy8hvwg+T+Y9Zn6ApI2/KTSJ9Jbjrxt2sx8sQCVyxwAV+9YfRzlY/D0/ng+947d5UjbDfkJZ1170xGkDyUazRpqTSivTmbLzp8bHfSmHvFRg5QxHjJE8D0RX5DO6tnhV81miOGCP0t+GTN+UGkc8Zde/ynjpTpqTTGqVxcv+gHnRUuCWMHPLaAxgkDJz3Bj1bKvIPgrOyL1lnKcUzcClVuNQToydl8WJlnXyw2wM4jqyjSQ+G3I2Ybhl1zMg8c5JBBAqV0I6l4P1uyL4E8aIVtoAiqrOWcc3RSJdM+jevOycwUpp7UTn7mfpEJQiX66MXjeJuhZ0E26b4z8fGdB6EcdUHYt22ZbkTks78TanIzhgQZ5RSnqfebJBNCRFz8iDIRv6x+2IMHxuA8pQfF3yFNwANwMrJmgtxM0hU3q3p/KDgWkGcrQQ==
    VIKUNJA_API_TOKEN: AgAlRdETNc7IjcZ6KPNBRXNjuczwaypP2j2ZH04i76XQICfvNn0xlmU9JbPIn13qrwzX/0yj0FsjUi6XY0dJSoKwzGBKNHjsSEc4RwiykODC8KSnVRd7E4QVbKZpRli0+gKcLMz2EDz8EQm+nnRmv1LRx6pWOBP9g0wS8rdsZrmPT0LpEDg9Z6vyX1zxPJXVpliyDpSCGpWDQOj1UPkGKiYghVqBb+cGH1tTtwIY2OR5e/dCEPLWgUPaI/C/jqD6cEMM6MA/VmxvrSzNq1t8DaxQMdtZa7+Z8qmaRXl6QE/TuHHi/o8/Wu/NDqLSBRm9d28SoazUPnwRhGF6zyoNbnxwn0z+xuFrBBKAs0bWlZ9kyltjqTkuBvROLj/nAoFteK5N8Ihovl+bqUWXE9t0tyxLXJGcP3uaO4mvPIe6D9KiexaXogb4LrK12z4LbcOsZAJKOfSjWQf9j0tKcQ2EWE13OxX5Hw1FhrtyaVSPrKf/A0TTgogdBQLtspxODJ3tEOWw18sAOirFIZEjMj0E/YuLaxCEgbXJ5V66O3j+SiVtVox4SXHDyqdhzM1tPmTj6E02S7JJ0tKMsJEyxaTdvrCxUpS4lfZTo+6cGJqFYa70rfDZNXqhKFTXlqT36NNRthyy6SVdgzzBv67ALfraIMuC/VDFRz/YBI0JHcZS/DJqiWSm9lM5xU7D87DhJlY/TEXRvr55GgyRTmQk9+Z0xw7WzrS0jJw7rQYhkHYN/RpGZfmDPD6MTlLRbCOi
  template:
    metadata:
      name: mcp-personal-t
      namespace: mcp-personal
