---
apiVersion: v1
kind: Service
metadata:
  name: mcp-vikunja-s
  namespace: mcp-personal
spec:
  selector:
    app: mcp-vikunja-s
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
