---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../helmrepositories
  - ../kube-system
  - ../metrics-server
  - ../kube-state-metrics
  - ../node-exporter
  - ../spegel
  - ../storage
