---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-ingest
  namespace: radarr
spec:
  storageClassName: ""
  volumeName: radarr-ingest-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
