---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
  namespace: radarr
spec:
  storageClassName: ""
  volumeName: radarr-movies-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
