---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-apikey
  namespace: radarr
spec:
  encryptedData:
    apikey: AgBrNY57zI9P9hcMwFehw2Av8ww3s3YWOSAHjFMss/XOdK3bc9AxVU3DZ8lcsTlLKVlkU3ETEKBethemG8SFoGosKbQSuYrNoS/J3yBiDnwb8anyl12u9Nejqwc3a4JVhF7b9o3QMOh04+5si6hJBygo9qOXyKSxiC64rhh7h3wTD3NTXuzvwBUYnR/7p6QumhRTEIle6vVvmD716TdlCCjZrm5au4YcDDH0XWQQVWHf4iB61q5WipN8d/eqMAeey6+dlt6tNY3AJw++9RlqP4ZXjLPq5htJG2TVA8fqZBqjkp/ODShjUv/Xej2cz/x/6twOQ0HtT4q1Y3mI3O+QCOTRs8XbbxwzxFF+XGf1+yEvS2NiFsGZKs29OPtzZ06pB+ROU2tB/91bzLOTNmLFAFWc/qwTnNS/FWqwg1AV2O7IWS6mY5hBR9QpstrU+FJpnNtgAiiYWEQ8MqsJ+8c6lrY78GsmuHum48LC9GhgcIY59JZy58C8TvxdLk7pQuAYH+nR4lQDvPqeBrqyP2S5rT7j+6WjGPi6VXM9swgbRhVNDw75FHQLmDbh2TqPDy7OpvxNJzsRvVd55OB2sqV0/i9UfOtpJJxmdUfr8Pb8P/w6Xhi7LBOD9jd8TitIEyCdJdugtONXUh2mwBY8oyl7r4iZ/+Q9lSmFiFjgqZSCp4GDzJv40DmyA0AO3U2j54psbMfNEfSNzuAfqHmA5rLnaUtzr8lmWDu6yx2Pow1w0hAioA==
  template:
    metadata:
      name: radarr-apikey
      namespace: radarr
    type: Opaque
