---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-dc-data
  namespace: samba-dc
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
