---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-dc-secrets
  namespace: samba-dc
spec:
  encryptedData:
    admin-password: AgAn3KUNvyX1P2KLgoPfrll45eBd1sDX+Y6NIDhqey+XAHFwPh6Q5j+VNfUoUqgJM8RHmtNXZUx1mBRqUIHqKBk2Fq2gHAs9VhcWZzUP0SoWSLWR5esDVtjITBJfknqqom3azXEVH3xT1+juKsuHetaVu7S1HA0wQz01XqQD/TCBQKXs+M3k/jNxl47VmeWPXg7Sl3OOy2ROyh8EDMwGw9icQ3Zu2DZBt5SBhdKrNi/9OYhZPaJG4/SemXfzyzwv9zgtTkJLQA1WqSG0Rx4sBR3XXcOgb4O/LObNDB5jZk2mzqT2mspVqCgrkT266grj+iunf9D7yB7ooUwPjF40I1A/9UnhPHR7FQdKWWlaP9YmNkmAy4hxbZwJe5/BqZE44+uJKO8ckqOGRcUWV/TUuHrNKGdG/1kqWR6XyUQ0dHxgbHcSsv229q+eEaVm0RsWjn/bKpW1PyBjjbAL/hqbg7Ph/Pxz4DVdrMzli5nkX3VyST/7Zn4KhGN+lLTdDKh1Ku5RDOo+SiVvIh5LZL8px6bDaFFYXxxPqFgi/zpSmUGtlECZCGvzZu8FjpaNNlmt6th3kWPhAOEmaSKnG+HzOBPir8uYlrNWvlJkig7cZS6Y4UC/ZpgbsWP6GOPKWUIfrJwEc64QV8xzaOqc30SBEVgnr3lb+AufWOM0zMDwBPsZqcfVjhLx39upytMTfG9DHGw3EIyR1/Rw73+NFWaXMKijFGDZiRURTAj6vxwSQ5tPvbNB8687LMAv5ZBIHFfEcLsMjRc=
    nutanix-bind-password: AgCBzopPxsQ7+rncUCC3Ngu3zXALkFPAbyeYXmQf4YmlnbYW1/LIOZdcm9pYRYH0GrDX+g977RZKZ/Jrpph9n5Tk11/t03opuxEzaIFkskXp4p44owFnn6ASrWUHZXsSFd9/b+Q0L9NvFIKi+vYGyPlXiPaRerxDoMGHXPamkzpaTQCB0jte2osO/iRA5tFN6p7r7I8ak5cObJB+HdzxqPUE4txki/M7VyA/HoO5A6JfZGWQ3Ei7J+mLiCaDwT7/Uokbc4sG4hpTLZKUN3Wc/tL5xQlmDStPR2I9BjSnTJihEB94sTGQMtQHApA0yp3b60BcrghmtfhbKo86gr9vTNHf4709brU5XEbKFIA19vnk+MtgfkykGybY5q4WzAeCX7dsjprftzhxfGIVhAeJijh78YmeJAAzj4aFWB+oypXkwYODjjH47xoUxrhaZvCDObZogI22fd01mv0TiEfo8W/47586F6+QWn7B4js1R59a7l1ftWt4qjJlSh+g8kaqkru3ips0rUHJZUUZ6vQ1YXIH6uowQl+s0xjJuovz0t8xtuzY50g7/WwF17QKWcAon0ZjTmxoorsP+eCPjIyg6Dm1fFpgtnk6bj3y1DF3QwGt1OjbGDoLJCQeHBX6UJrW7lYc/iz0OaTwp51gAnRz4FAZQNIENYm4CnkC+CWOY1JUPhA6Uqg19HOlEf0QVbryHDJfkHftgmwEFKMW0OSDuM3C9QEbTwz3UvW6nuXx/3zwSDkYRlr+0gnogFfFiS9Qa3DUueQ=
  template:
    metadata:
      name: samba-dc-secrets
      namespace: samba-dc
    type: Opaque
