# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgCHwxys6FirV75Fyp7iv3R8xxBPtsVB7BRIWs3v10V/ALV0HzDAxqvMrXQjYgfT8Bkn5fJfhSsk+qteWIVIY7uYhxAxKIq9+OpKAGSOKLSkABKnhs5XdB7Kx+3m1cPT5HKNxtFzK9KQs8wx5Peh9FRszTYEl0mXtVZ8jSjkDD2+p4wojkguKoVYEvlhvQYXiIcF+1hLFGCm6SHjrie/PeImEcDcO6B/HSb1DOL8FPF/tXXvQn2i+Y9MoUXx8TXK5x4BYkOlLwDZhuo7OsaDyJo0/Yj/lvF67jB3NhvjJLe3ndn6MHyyhrjMdquhQy5w2oRDWhfKTY4ZzkW2teXir4taadRYdoDttK+Gj5Xzj4nI5ETsumeEQ5i7V7UFGJztH9bvJ6tSr67a0+49QrzsFKB2iHlDn1wohhqBNFU3Sn0ixx1uizuS3beK/9pNrrFtu2Hw7N+3r9o3fyY19eq24J7OPpcz7jzXY0qSebjsXdJu+uWjLOyG1vjjtS3e6O7twKWxyfIRPV4u7jcotxY8RMvrWdAmmca8Kka3c7XgoSu6xhf40U0d4TfnW1hGF7oK+7xa9pdJYW4MTtY7bUycSfTotUFeJfa22zDKUfm4WSV79viPfkN6G90r/YAjaCih3OFwGug9gE5z8w4kE0+MILjFnS48sopA7xG8SendU9BjqYRw223FwRuHGJwVzyIPS56nz8sz+1uhfWffIsKbkDu1rdOukkgEO0gVoL6dZj7RT7KZ2HBtFYKL7hXGwVeTpF50obue1w2MeTiaPWtAMX2T8J7YxYNnM8Tl8s8zIXK8FN7/dMDsh329dTGfJDNv+NeVv4emNaaWn6YMSndZxJyiLGeBDkaJ4h9c5WXNpZO6o001xd1WG1PuJkreMsxUkX3geHNdEMJhTTPD6RnqsWxnNBxn39cPG7shKyJDanQ7BjWDUl8pwSKuY3juok1V1uUCwbA5sdmL8SbgRiiEpbr8x6wxywpR64/nccmz2H3D4ZA29vMuNLDD5HgLQkk8N9QINQtHzllrGuqx6/O1y5Gez7T5QFyvBH4anIS+/Hjm2+Jn81SbhkkKSx4GNwb2UcZjhX1f7x96dpHqG93M5vIwHGwzTSj2Vdrq79XaLGRidtlMjzJUhLXz98BACKl59Hc+pHdsPhLyPkmXoIEljXF9kT96D9U1sRaJh2o=
  template:
    metadata:
      name: immich-config
      namespace: immich
    type: Opaque
