# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgAmczrUTC25VLFHJF7L8PU5AZhgvrjSMvq4GfRgOjt8LY4e7P/xFTdcJ+a8HR4r03KI54PthFT3UD9DdLmoKPnDkDa8sUxlA0EF27AFcwr5Gv7fKt3/qTEcvnOZFe5EKN4mmmOOc5g76ZDkza+Kb+J39GC2k9rOKeJWCas4mMIkXS0wbyqOAX78hZLEFHPIwJ23manrB0OrviDFivYnJjGGdykkJhVOy6rzhKvZ2CNxH3Q1zvZcJdfhBNWKImfBMAEJCciItKLqYOQxXVOVGmhZC0WMoFfDnbXV3ITsxz/BfpSH0phMTZ8CCDo5ciRiK7/lktFqvVspcj3Sfaz19WS5MaGumFCI8PMjedCG4GTCO0LHMJo7l6JLkE3NR0UyVi8v4G0CvQqK6ME0yo4jZJEqCxAkSgKJQvnWK6E34IWuNskpy1nhBNoVB4MGBvQKqyf/7+2si0N5wpFFT+sgaLgBGWL0DRJOyiEyZEhdRJZQgZ8/gf+XJIhYfZ7bfW/6XgxjT6wzSkULeEE50ZJsIvvKNhXkVA3cOOFhzOn2QTUuUjb7bgrV1Xx+H3g+PkbP8X0QPv+ereUSa0iS6rSPZ9wFa0MjDvRyoGzJDDzKPmXUngUEDE+m7g/5gmpSlmca4qlQAwD5YFfGQffyQ8ca1YRRyTtpvGalxWVzc2icOLagg+qNUzUqzQqaDV+ZJufub2+wWxj8uWlb1pl/XCsXje5gZfz+hWlsz+SO05AxyE8MbJbX6H4XoA4sN8jQpTiyHpNnl9fxYh/FMG/dkWDAJ1hpcRAAmSgBbkbS918DMLiYeWZhOyqfhSzfSSJQzt5PBTfRPLZzItYPXYpik/3q6YKWR5RxPvbL93OL5NuwzZ1X39woW+12nIu45NJDBFk9szZkdv8ILEY8+PEuL5K2zY0orcNKPN+tAWA9Ky/T8Of1Zc5WSEiDuzY4WopZRejtu7qoRR4cWyPsyQkt8wqnQlJrQ01udrNaru0IFJ9e0XRtlvtjqeHuPfv+pdglrvQpHlE0hVxf4ECbXWV8257jpXT0sJAl9f8N5oUEXCKgehhDgyp+dvWryKRFvCp5UkvnWMMS6KiqUVTkXEfKloBA+IiHidVz8DRI3nCA7OHUXqwn3IeFWN2cA7fwG6JYgoTTOKuNdov6AH/ZqJRAYEGSjoJGZWfFSMSgQwjNVA0=
  template:
    metadata:
      name: immich-config
      namespace: immich
    type: Opaque
