# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgCt2H9kWpoCzSF9KtWzglV3aNM3hgNF5826qbBWD8dpBH2/xZ00IzBVewzWw21hHRaNDoHgsXDfMURSFhWJ/ByKcOqBKjLMpP5yRNlFpdkGEnAxTRSl0daxVcpLElv2hb2GIkBXVppv3U67hCupoexsMNtvHHsgn6azlCp2AewSjeB44z/pkl2sIT6/JMf0qEqoJSEvH+B9PPYljmdZhG6kNOZ9PUG3NrhmxFjX4FqVdimqdoAU4T8wVLzkWXawh+6i3JmjqyCauM3rzfddA/0f/HZ8++FUly/tNtK/InJrzOnFJN+YgjJSsKsfsouUIt4aMCaZ3sfFv9YXzQGzL/oiWiSDwv8yrpk5t1B1u3YRWiU95IWDgkFFz+3MfmQ6gCppFUR26cKobkblulp3AaAgkJ73VzVjiROPxLXZr16Pa1wgeGJ7PiAOLYMKqbFzeaYWpZybHWyO9+iFniKT5j71cKKPoGBEgvLqTlnJ4bj/1lXeYs8/u1ApE1H5fvF28wEc5kkMS8PN6FR7MYJ+1sMn1dwB+H++TnuM5RXiBLXmXFG6bhgyayRfXKG3vJmSoxa680n/dgef5u2RbNpkUy2yk0Dja2PVEBFfIzna1MdNv3bw/Z95Sgs3U+xz2LQP8BSRN1GNYWWfMLhRd3Lti9Ze0ucz68iLIXZxokAcUthgRRLQPThkiJXQtTyYaDtlGLY62Ijt2xWn3I48zoc2f7febnenHt3GHn9qS0ethC0uZusk5KOIcW4wip7/dZP8aFMJw4OwbVd8y2qEARECFpKh51nSlJ7UjTONeoJGitU6D06pci4aJxlvDzerU69Hec/dWFtYPiBfqePQcfv9rStdhanzlrTJw+dZpoyL4FmrY+U1s9gdHExdnm7UfmX5U9GhMXVVh9Sk10ONoj/ZJTSba7pEafJXjbvCMgGH3NG4OPKB+C4iSSc6yaQd5ZXom7fg+pOe8dUCHlQxg36j02WMijmE+T+fpATf4wY/xHmSAlebML8qSC6Il/UQmw+vZcuMgA3sPbYHgxCF00Ss0MZW48mvSPbK12wpU51EMhVuNq7qwAoZhJ2zd3wnYWqgmn0DSP04/0J/wxpgEJSrHtONjeehC3W0lsJ956K11p3yo5Qx659ZQN6i89eA+oM2R1mogMfKKe2RazhRAAmkFmLe99X7ntgcFii5JcY=
  template:
    metadata:
      name: immich-config
      namespace: immich
    type: Opaque
