---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-sync
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - name: sync-tcp
      protocol: TCP
      port: 22000
      targetPort: 22000
    - name: sync-quic
      protocol: UDP
      port: 22000
      targetPort: 22000
    - name: discovery
      protocol: UDP
      port: 21027
      targetPort: 21027
  # Syncthing needs external access for device-to-device sync
  type: LoadBalancer
