---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: garage
  namespace: garage
  labels:
    app: garage
spec:
  selector:
    matchLabels:
      app: garage
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - garage
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
